#!/usr/bin/env python3
"""
Atualiza um dashboard HTML com dados Financeiros (extrato de contas
bancárias + cartões de crédito) puxados direto da API da Omie.

A página gerada tem filtros INTERATIVOS (em JavaScript, no navegador):
- Painel superior: quais contas/cartões exibir, período, conciliação,
  cliente/fornecedor, valor, situação
- Filtro estilo Excel em cada coluna das tabelas (clique na seta do
  cabeçalho para escolher valores específicos)

Para isso, o script busca TODOS os lançamentos brutos de 01/01/2026 até
a data de hoje (a cada execução, mês a mês para evitar o limite de 100
registros por chamada da Omie), e embute esses dados na própria página.
Os filtros só reorganizam o que já foi baixado — não fazem nova chamada
à Omie a cada clique.
"""

import os
import json as jsonlib
import time
from datetime import datetime, timezone, timedelta
import requests

def _credenciais(env_key: str, env_secret: str):
    """Lê um par de credenciais do ambiente. Se não estiverem configuradas
    (ainda não criamos os Secrets no GitHub para aquela empresa), retorna
    (None, None) — a empresa correspondente simplesmente não entra na
    busca, sem quebrar o script."""
    key = os.environ.get(env_key)
    secret = os.environ.get(env_secret)
    return (key, secret) if key and secret else (None, None)


BASE_URL = "https://app.omie.com.br/api/v1"
HEADERS = {"Content-Type": "application/json"}

# Período de busca: sempre de 01/01/2026 até 1 ano a partir do dia da execução
PERIODO_INICIAL = "01/01/2026"
PERIODO_FINAL = (datetime.now() + timedelta(days=365)).strftime("%d/%m/%Y")

# Logo da Prime Sol (ícone, fundo transparente), embutida como base64 para
# o arquivo continuar sendo um único script — sem depender de outro arquivo
# no repositório.
LOGO_BASE64 = "iVBORw0KGgoAAAANSUhEUgAAAM4AAABvCAYAAACkX/+PAABhKUlEQVR4nO39SbNkR5Lvif3U7Jzj7neOGzMiEBGIAJBIIJHIBBKVNbyqfv2qRB6F0sseRMhNb3pFfgbuKMIthV+BIhRShDtuSPbr1+yqrByRAzKRmAKIAUDMw53d/RwzUy7UzuA3IgcAkZkACgYJ3Mn9uB07pqaqf/2rqqgqX+6RgAgIpAIEkDmBwJwCwbOkhb1MAAmQBFRBCnD2uybUFMUYgJgavHNIHcFXgAOB6OyTEgGAksLe/iRuQQDZBxRlTMQhNAC4NEIkvzDeV9InsH8Ztt6FvV04810oT8HoLMiG4NZRV1BLQgGHowREG4g1yMjuKd9X9+/r8UeP4i89gScxFEHaTQC0m8Lj7PeKbU6vIA48gNjvVQGlLErIG7VwkFSRckyY1hTjCsTe5jDhgXwZ5fNvuu79RZ5ogQCKsz0toA1IGYE5XP0VH731/0Wau1RlwfS3l5msP82R089Tnn5O2TyHsMyIChgJOgFKSBGKAlC0CYgv7eJfC82nHvJl1zgKRBLgTC6AKCH/pcQrJg8O8FAL1AQcypgClwCJEKfga9CkuEqUJTSWSFYpAllikl0LTAVJvvbn2XztI5CUf3aoQEPA4ShiFv64Dc17ev1//r/gppeR2YylyQinoCo0mkjFCL90ipUT32B89juw+SLoccGvEFCSz4KDIlQIJq5fy86nG18JjdPvZBvtPiw0/+DpdoYolAKegGMfmCnpALZusH/nI5bWl9HxurqjFxF3WmIqcB5ME+SR8uc9SRNHTMO0cxQwU7L9HAXcVO+/+0PSwVU2R3uUo4ow20G0pigSHqVJynz7Fnt7V9m58Q46OsfJi3+rnHyJYvWszKlQomliEvK1nfaZxpdecIRsMmEbrt0Did4EUdfYt1pSpgh+Dmwrs09g/yr7b/6PHNy7ChrZRXBrxzjxrX+Cp/6jen/SrqKS5dN15lnMGsJlk+qz34RpzFY0WxPQtRdVQA+A+8zuvM2ybCPz+6YRU4IJhJhwjafCMXKBoA84mO0w23+POwfvMNn6O1a/999rxbKQ55tig3NZ53wtO59qfOkFB7LAtP9MQuwP+UvUSCEB0hTSVNEduP8ODz/4Fx5ef4MjeofjVWQ+rdGiot65x7Uf7XL+f/UcrExAl4Cy31z5s1TIRuKTGIMr5c9pD4SQoPAzuPceo+YGVZqyVDhCExhVY2bSmLaKDkkOKRKlC6y6GZNizu7Bezz8aMTqC/8VaXwU7ysTzOjN5/taaD71+AoIzsCEyuaHJwDmJwAUjEG3INxUbr7J7OpP2Ln7NsQHHCtmTGiYTqc4GeNFWK4iO8097l3+Ace+c0pJS4IUqAQgIdlU884hC5//+Uanc6Q32QB8CeiecutXpJ2PGI8K4txRVmNC3RCjo/AVRTUCQHVOHRo0mAe4OVpmVu/BwQP8pM7rVID/Wmg+6/gKCI4JCy1cKxEh4Vt/gQQ8JNz4ue5/8M80t39NOb/JuttDXDB4FigKg64h0kz3WK4K7l75Mce+8T2oTgATFiA0fTK4wHC0royaoQma/RBpgANuXvkFJ1eVem9OKSUEQdQxcoImJdZ2L6kUKEpKDEqfTxvKsgL14DykBpyg4omA/xpY+9TjyVgZf8GhgIpDxeW7MZOnc3l1C+78J7384/8z9Z3/D0fcFZb1PlUzp/IOgsM5R0wNKU1xLuG9p2gOOFM+YPuN/xewrwZ6g6qhaio9CPEkRkqtqebQztRU0ADM4OEn+LBHM92iKsXMxCg4VyApIDrD+4DziUYDQZQo0CSBYp0oK7DxFFCiDlQSURJRnuRd/NsZXwGN08dVCs2Ys0DnxHOg9977XzjCx6zoNi41iCvAFWiMiEjegA4RJWmDJEcZI27vDnXzIWxfg40NSA7RUQdtawqIazfe5zuDnMvvV+3nDxjctqc7N97FaQOagQRRRFInBIa6KeIE54RGI5FEciWNjjl+7nlwpoEEn5G1NmLkPvf8/62Nr8BqJRIN5Gg+WgAjFG8+jgbuf/QeSzqnFEcThaYQYgVzbaCApIK4ClxENeJTwZgRVQN+7z77H/4IuKsEEJztbQEn6cn4OOo6swwSTn3vummC+ICH19+kkGT3RYO4QHAzkgtE8UR1JBVS5jagAU1zklMO3JjimW+C95ACIEhj8eA29vX1+HTjKyA4Az9jAKal1tUWx/LSOikKQkFSIYqnESFJIgkkcZm4o2i78cR21djPeHj9R7D9Lrg5dsnErN436emwr88+UqbcKBFpTaeU/2kD995D965TEFHxqKppRxqSiyCKc46UAiEEXFRKcXgEpSKOT8LmOZDKMHX12InhLSalX4lt8GcdX/oVExyeEk9hp7MEEg2RlOVowqlnX2M3rDLTEepLkno0mX+QUsI5SKj5LZJIMgPdR6UmFge4+AGza/8zuAeKq4lEpKoIlNSp6AKXn/keMipgfo6CJJu9A9jX5vovWdUtnM7wIqToEPE55N/gyAFQJ7ikFMlRaYnXgiaOWT35EviTIGPwRaYdFRhX7Uu/Bf4i4yuxal0cR2zjGUutDUp6KZ76Nrp0jln0FFJQqlIki7SnFFCNdtqrw7sS5xxBlJoEUrPiD3j40W+guQdhSx01ghCTIbqfZyh0YAMpx1qJON+AzCHcY+vGuyz7GTT7iCbDDJLHqwf1pNbJy/6WQ5BkrFRlxMa5V0A2BSoUiwtp+5lPEhb8NzS+AoKTLL4iFrtBS0QdhYJvg4qrlzh+/q9JOqJIgTLMKLUGTTgvqNR4jZRB8dEbh8uNEVfitKSqHX53D668BXEH0YYS8KF5Ij5CNg7xWoJ6Ig0qe+DuKffeJc0eUKYZPs1wLpim1AKnS0gcE9MSIY1pFNQL0SWa1KAijJc3YfMCyCog5pN5+8yW7f01rvbpx1dAcA6RooXsG+R/lOCOyfjC94jlJkHGBimT0JhwzuG94DKdJoZEjBZJSThijHgiS27Onbf/BcJdaBGpUrKzPQQI0qF/v3/Yq/LrXKsCQGiU8JD9O++x5CKEBnGKc1A6QWJC1cy2MqNliqBewSUaUeLoKOMjF6BYR1ufRnvqXurM2a/Hpx1ffsFRZ3k4WqBEY0Z3SK4DmYCsw9JTrF94jZ1yk3m1QsThfYE0AkHQ5IjOkQqHiqCSCB60TCBTRrJNMf0A3v8BaFClIKRgsBQwFBYd/OuEZ0gLov8VGNdt+MuCcSaSztn++H2KUOMQUuFoUoTY4AmImn/mnaLNDNTEPTJHiwl363WKl/4JZNLz7aKz90FOu/h6fJbx5Rcc6DZkq2gWfo8jaQHVpkwu/jUH7iRzN0J9gYjHiXSbJ7UxGUmI2j8jpTVo3GPitnl489dwcBuJexRe+mDl75na414y/JUAGg0MSEkz0hXh5jswv4nINAcszbzqKAaSEAKaalyLxomFfmstGW0+B9VJkPKRD32SVKF/i+OrITidg5sT2trRnvAu2uZZf57Np14lphJINLHODrUiRHxKOCJeE0WCKkIVzdH23iNpSty/xfTyD4AHCk1OlGsh3cwBIyNWf1Rg0YBzJRqq5zOa5mbs3PgZXm6gxQ7Bz01hSEFghIrHEREikiLOFTmhrwKtiGnM0TPPw3ijn0N7Qjxh1sO/xfHlFxzB0DRJuPwf0AZzQBOKkvCQjsryN/6Bxm0SZIQ4R0pt3Mb4YU4doopgwuMTBv0C4hoq2eXB1R9DcwPqAzWhof/MbvwhoRn6QA7vPYmEkwhpH9Ieu3cvs1TMsuYrEPVI8iRxRHEk6aJViJh/lCgIsUT9Kv7k8xkUaGNa/ZTSI3P4enya8eUXnIE/IbgBNL34KmUEsgFLz7B2+mWmukIxXiameWYY5MCgBXMsnJIRMxVPow1FqUh4QDm/Bu/+C7ga4mIKw6c/yp2Fn5Bcy2AfZEe5eZnR/h6TWijCBIlLlGFMGQuL87iE4loEm14UPI1OGK0+DWvnQdYk4u3vLnW5P/17vhaezzK+9ILTKpbuh+HGdcaaNvSoAOdA1mXy4n/JnpxkvxF8UeS3epSKRJW1WH+hJIIrC5owpSpqJm6be1d+BvMHoLPMH/s94xEPPLOf283e5fUIorWSdti/9hZLJKTu51EkwSmmgSQaioZHnRibgAQqJLfO+slvQLlpZh1Fvyx5Ll/6B/8XHl+B9XucL5FPVgdRQCjNlREgetj4JqtP/w0HzRhXjrv3R0oSJcE588/F3p+8kJwQNOG9UugeaX4XPvg5xG2F+R8O5nT+xaP5Q9Jt5szpnt1j7/b7lC2TwU9Rf4Awp9CAp0E0mclGYQpSE07y78pNOPMSsCy9PhlAz8qiL/j1+NTjK7J6WXAWoCozfCLgdLBNCg8cl40X/5FQnWAWqu78N9ax67RYdJnHJjCbzRiPlpjP5zgXGMk+tz/4Vwg3gQOMZJr9jd81TXlUMzno+HEx5SDU1nXC7DYx1WjhiL4hudpY0Bgi1qJi6kwgogY8ilJQF0dh8xmgWvikNtG71cxfkYf/Fxlf+rXrWCOH8F0DBA5v1JBfuALL59k89z2mskEMQukgxjmQEA9RjU8TVdAQWR4vE+YBp46yLCHuUM6vwof/DOwq0oA0qNbE2HSf2MPVhzVN/09UcDi88xBmNHffZzSesR8PSEVBFEdAiFKhUoIWpATiAkUhRAkUpeUUNcFx7MK3QdbQRge6+JBWzlrHqElf+m3wZx9fiRXrTnjtfzGkkrj8N9Vofo46YFUml/6aA3+cYmmVJswpPRSlEpqaonCkZChbJSVx1lAVYwpXcnCwx6hsWPH3uP3eP0P9AGhALbrvvWkOzQDxH3S+Ux9LovB8dP1dYtxlNHYEDVTOU+ZHlQTElXjvIQbq+T7ee2Jy4CdEv0x15gWQFZGyeDx3uwvGfiUe/19kfCVXrjWazHXOadUyMKQUYxtsXGL19HfZq8ssZHOczjPvzZSTE8EF8FFw0c7oUTGilIhLdyn0DrObVzDB6T0KoWU7D8ejAiQKXoRmnmjqGUhgPB5TCEisqWKAvQOKuqGgQWloUrQ0CRHKsiSERKRkzgS/fCqnEIxB1K7PIfPxEdj86/Fpx1d01ey2fGeE2OnvXNnlvlg0fZ3NF/+OGetItWHM4TCnLD2hmeNEKVTwFJSuIoVICAERIcZIE2aUpePWrRvDj0VzGnSX1bkwHoV/Q4iUlaOqCpgnljfOEmWdhgqcpxqP8UVBlJpERFyB8yOgoGkUTQ5XrnCgG2yc/RakJRMcu/owfGPja57N5x5fHcHpigzYCeuzBd/BvqKAQ9oifw6axgtr5zl6/vvss0ksxiQizpckFYjBqC/iQBXxVjknNIqUE9zoKDuNp6gm9N5W70to6kGH3zVUoKgSKjP7Rbku69/4J6rN7zBjk303Zj8ptUSSM6SwUUeTPKJjSr9C6Veo04RZcQrOfRdkguKMzCoGdbSz0+FatQVOvh6fenzpaw6Y1dEX6IDW/OlvLWrAiSOFQf6M87jROtAwfuEfuPvR2zjdohSYh4gvCzQkk5n5DEpPcgKuxEnFrC44iCWsnObs+ecBZzZikYVTrXzA42fcMwYgEUk2e1VgDMsX2Xj9v4Xbz3H3yo/Y2bnGKB0wJnQVaVKsiTGCJApfsbOvuFPnYO0ceIOhkUF+6jAovBA0Hc7l6/HHji+94EDbqyCZUCTXOjgWx+lo+j2ROThLdxMgNQ63cpGNM99j+vFNREpAGfkCTQ1IJHlFXSI4pVEo1RHSEiydY/Pp1+DoOWwpy8w+sA/8Y0I7hnuNDDZPDc6NwJ8UxhvwzLMcP/uPSrxH/Phdtq/8mtnWFZzepfSRqlS8QKiFycpRVp551dgRVDggithUBgLc8QYeQVS+Hp9mPHnBORRLaXMS4RBkfHjIpz352i2QHvnYDjUSS3HpzDOf/fcCaoVSHEW5KjSiq9/6B3bu/AhX7zD2kRjmtvlSxI3HbM0iWq0TWGY3rHDymW/jn/8+rF4Ali2w6o2yownEw2NdnMeIU0r2WudL0yLeEyio3DIyOiLoafyzF3Tzwvdh/yO4/SYPP36LO1s3kagsL2+yfvYV/KXvg1uTFO3zB8bZ4icvTOFx4n0YOl9c2se93mo+tK+d2z+dqpW3AmupsixtIRVaetTvm8YXeDyRbgU9CpxzcrsTf55h4VEmUP4O4Wnj2wKtj/DYlz2SMGYPyjKHHV1t9AEs3ZFAu7m6LuPSclJA0hzqqzp7///B3ff+E8vNPVZkRhEDrqw4EM9Ws0Q9vsDR899n9Zl/B2tP5bz9EbAi9hW7/9+5CR6/IYfTfdzPEEBrKyRIAJkqOoODA3Q+R44cBRmBWxUrnOi7NeyeSb5gp4EeO8eEqmbCa++fqbq2KlVXHXXxEo2tfSyNu1fcU5ob8MkvmH7yHl4T1dlvwoW/JcVVtDwiUOJDntcjsN8Xf/wJNM6QRPiY0eWSPO6P2almKBbtS9tNt+jM6qHv5fB1c05OJ5xYlU8/MOFSSLhqk/HJV9EbNzjYusx41NCEOXvTmrR8jJMvvIZ/5u9h7XnguKBjkoJIG0A8RN1/7Hj8uhx+y6OXKOyUdpPMgjbUQVeUtGQFFB/3OdJ+P7ig/J45qrFdEXULJ5yIaTD7jQ6EClRrnOxCnCtxLOiehg/+hZtX/gW/c4UlDqCuuf/Jz0nX3+XMv//fgpaoHOGPCXF9UccT0jg9FaTLTRFAQo6cS/57a1opSiBl78Rj0OoCYZNBmg1pkUgppjnS8FQlLUbBHzEDDsHA3bGuQLDTPE2VrWtsffCvfHztl4zGjrMXvsnk6dfN6ZZVYGT8YrcEWphZ1k/0Tz7seQ1TCR43Pp2jb5at4tIhCZO0aE2gOVWcDOcXwD5wQwn34f3fsPX+j5g171CUu6QY8aFhrRT2a+FhWuXCa/818uz/BuS0aJuu8alm+8UYT0xwpNMRhzljLWMMeo1iCb7adkBjBJR/WHBEzVYQ15lcYA/VDXSUHDKDFh9MGrCo8zVzwJNYQJyB3FX8FFwDoQR3RpAVkjrUOaDB4dFgdrr8iTszWR214SkfaZ+biDxGgD6d4KT8vDoibPtV2kMxQU7VNrgwgjaQZgpb6LUfcv+Dn8CD66xVu6h+QpP20XLZKErNjGq8xEF03OciT/+v/09QPivqxwSEAv+lE54nYqr1G9U9ZqPaRrNRZk0BSkGizJVoADWWsB8IRM81S7lXTAtVDU0Rstk1BApC99k5FGmvH9JM2u+zdEYC3kkOHJ60UpckKCpgiZiM7Gn7yRNiwEv1Z9U27RDxj5qkn+d6C9ykPPLhIs7RxJrCZ3st1aC7SrwHH/2Q+x/8mOnDq6xVkSTbTPd3WK2USibUU+P1xTrQ1HMmVckKO8R3fox/+biKJkGGMbAvz3iirQwXFE33Q8I2oQPtc991Aa7NAjJwPNPw9wuL6h5Z4kV0xk5I7Yw4t/CeLtGt/SCXqfuYQyzqICni2iCmmWIqXYve7lopKqpKUfx5HvpQyzy5i3KI1JcWDxcU3AyYGkoWt+DqL7n53r8Qt95hbbSPTzOaZp9y5BgXHj/LWl0c8/mc0dISaT7DOWXmjnC/eJkz/9X/DkYXRVlf9BG/JONPEsdZRM4cFt/o6ezGzM3f57yZ4boJbeCuRdfcggn3yGe1SJrLnzeIiB9+HDpgGPQ6zdG1ERQQJ511KQJEC4QWRGIy20y8y2TOP5+6EbGEteFhp6q/g9rzx1508P0CkEIOyDYQD2B6Xbn1Yx5c+zFh+wNWmOJGEOt9vEuU44JpCuzNEuM4gZhQN6VaHjGdBRwlI0DCjEquw/UfwaWnVGRDvozVRJ+o4PzOLbRgHgHsAVM1R7MARtL1dJaC/vuhOXb4moc++JBAPHZeWdP1iV2mQ1TBiWmlhWYB7WVEQDKQ4dve01gVUFlkKfwpxtDHOaxtnrj2kQA6B6aKTkF32H/rJ+ze+g3NgzeZcJu1cg+JNZoqxn5MjA0SHJX3VmIrQTlyaOGZNfuUk3Xm05oiCVVV4OJ9bl3+Eacu/hOwiXW7+3LF4p/IbLtGSNBrluFG7gSmAXmgxGvEa2/i5wH8Mjz9slJsQLEMMhHcOAMAtpG7ThqE/AuxQKN6ky9n5llasDs6MHZByMzUMppLq28qWZyz9i+096gsLlXWaP1B/wcg+M85nqhwYKztDlTQBqS2ddURFrDcUubXidd+wI33f8ho/oCJ7rPq5pRaI1ERPLiIpCkFHqIgKeElEYuauUScNkgBMR2YtixGzAm4IlFPb8D1n8OZiVKelC8bieWJzfZxoZnOSZcC0QZkS7n3a9574//Oit7HHdR4WWL/rf+JI6efY/3cC3D0nFIdBVlGWBYrdwQ5FD6QC8klxBIhxaygZCHK8Kg3ZO+32Ev7muENpI4Gs6CzZIjwHb7rL/447BstIHGSzHdhbnbv3l3qj37B3Ws/gv132Sy38OzkAogFTi3/1GWVbEibnTZeHbhkYYa27aNC5ZSZBmBE08ypljxV3OOjd3/A00+/ArqJgQRfnvGEBOewKWYjZTTNqQedgdzhk3f/E+y+TeF3KOeJoijw44KdG7/g4UcjRpMTbB5/gdGJb8Kx55TJU+COCCxDKkiu6IgkKTWICN6VJKCJFhqsBvKSUjBErjO7TLt4cbjWtk4YCqBNNg8dDp+BBXtBIuHyckl2fAdVn5/MMv6ZRusnmW+U7NmEm9Qf/oBb7/+Q0fQ2a7KL1Lv4Zo4v2gMwWfhY2zbyzUBAClCHU4dLJeAoUsJpIsaGpckK9TwyLjwSapp4QL17w4ounjn9F1qJzz6erH48hG71gdEIMlMefsDerTd5aiXiDvYYlwXIjLqZMi4dUo4IYY/da5/w4NrPqVbOUq6dZ/XE8ypPvwiTYzg3AS3FsiAdikeDWosLZ4LTTsP6W1pfz55nkkAHAtDOWxYhbesj2v651z+HPAy+DEKzGAPSRUBBp7D3AVd/8H+j2X6bU6sNLt1B6ilLS8uQPEFDptqYSdoCKk5z8y4C6pK1jsfhksNpylrJoS4wnx5QVRNSE4ipZjLZZF8dVOXjVPkXfjwxwVmoZyYQMy/A+GMJdM7s6hsc9Xvo9kN8DPhqRD0LjIoRYdYQpWZUQFVGos5ppjeJs1+xfX+V6dtLjDef4ciz34PT31LiBg2rlH5DRAVCadtYcnqxz8SUBZNkaIAd9lkwuLwNjJI6dOmxcKliAvhEgLXDmOGT95eG5pqhgfmBpS2986P/K6v7vwKZwTThfUkx8mhIxJhwvugpgJkRghakDPrkJtzG5dCehW5VghLRW8NEjTO8ePxoldt7Sjx6Eo5dAsonfr9/6vHkNM5wA0n7WPLlgwJz9m69zyQ+ZEKyDEaHdQoQT1VYoT11Qkw1aI1LAZwQ4x1Kv8Ls7h0+vvserJ5ncvIFjpx9EY4+o+gy6BjcRHAjHBMLP0hrSGXjriN7ZpoNRQ8GMIzxuIEAOTq49BHolsc7d1/QcRhkiDHiD3bQvWssN3dQKZHoscY/gjohhERB0cGNmc7WMUXMHzQGhrTrnQGi6CLRQVBlebzMdGsfkRHBHyWsnOXsi/8BdJWutvWXaDwBwRlwwDKkaJZ/QcqtWZEEDx/A7A7M7loCWR2oZUpyisZoFBaBGA0bc26MKwURTx0SIgUTjVTxIXF7n7D1Hg/f/3+j1RpHz7+MHL0Axy4p49OgR0BXRZjk+bTVXHJFywFsbZEK2wReMsO6Nd3EdYIVu3u1vjsibhFm/4ILz2FzDQxd8ynRHATGkwkpCDE2lKOC0MyZzedMlpcIIdLmGUkbe2t5bJLwGlEcVvjQdQIWfGOeoY7Y2VEmy0+zq2ukI9/mzAt/D2deATbk36zGsUfSnuJ9WoDR9hPoAbMPf41r9lleqmD/gHajmq+eW2uodgUyxDk0Ck0KoA4l4dMc6145QzRCo0Qdcefdj6mrTfzkJCvHLrF29hU4/oKix/C6KurGg3Cow7FYSbOvpGap0W1rwaHQ9KHS1MMB7esYfH2k4OCj2NswrjQkUsIfaLsxEND2PY8DwheucejDFUXV/MGyLGGywvLGKQ527uJjw6jyhPkBqpFqPKJpAoJH1KFiPmDEgQQ7QLR90tKZwpprWzdMSIxo0hpu6Rj1yimOvfj38NRr4I5JSBXiRvlQe8ydtPc7/Pq48Rc4tJ6A4OSTVxOWnx+7CKLdzwGk67p185esuIJUe1yVICV8qqBJpMIRSYgkJK+O5v58hUi2oRPJW0wnEhGcRfg1sKYHiAbC7l304EPuXP9npuVxzrzwjxTP/nsVPSvIpOPAdbk7mhDRQctyG60t3wZKFyGAQWH3/Lo84cWvXUzIdTpZ1ITS0ZqFBlqY/5DreOrALQNibPCuPZFbLp5xwdsSWG1siu774V5aZIuLiK0bOf5WLnHk2de484uPWS33qMMOVeEIMZnPlxwuNXjv0dzEsXHWk2cUrVNC9CPTYhrxYs8mMSGlFfZlk6VT3+HIM6/DmW+DWwPGoowoXNsmJQ7OBPfoYbQgMO06HxKyP7PwPBkfpw21a1z4tWmbfeXgQzw30fk+09QwWSosVTgExFW5YS04NbqHaEuAMRBYsknlBovVVrVEAoUqOt9nIko9v8vaeBk/3+L+e4mTk2V4ahPvJ485sFyfdNdFO8mf3L4ixyuG73mcaSZDqsHi0qQsDCItjN7WPjDp8izukZRo29zgfdlppoV5D65vguLyX9KhqbV+Go8/sWUEp1+GD39N2L+MSztdxLkh4MsRXsuMhgFFYR2vE0RVCm9CHaLgyjGpGHNQl8zSKhtnX2bj0t/A8ZfAHQe3JppGRNNheW49x/2xi9f5zj3htxt/wbpwn1twMpsJJ8kYtJhPYbF2B8yZXvkxLn7C8iSgjUdLT6NKKCPjUknNQCiyWZYGqltahz2bUpCsTTkBlYQvKus05gQvCXGJsc7Y3n6X7Q9/yPrpf6fEI1L4w5vPDTTDoqngh5vscQ9oQFDoaTw9pN2d+tpb8EoikHAuB2rFmSMeFJEERUScECXnJmU8w/lH973P/4b8P5vCkAWRFjfdob1pP06E1ed14+zrbL3zIWVhzzN4qNOUsghorXjvKbwjSU2pHsXa3k9jpPCJYrLMblxjL22ydPY7nH7u+3Dihez8LwmphOQz50/pu0KUXWy7vYfuGdO2aOmfWDtvJ9nP/AuNJxjH6U/chWh8gtn0PlH3qfUAUoM2AqXHpcQ81hTODwKUrTmiOf1GTJg6Zzx/RnsKJ0eKag1lQ6IoSubzgHjHelXy8N4N1gm0Hanzhwxn2Zk+C3MfILYLQwabMCfspe4a/UoYFO86s0tTAKeUmd3Qfq44lyXA0+YFte8n/7pNjej8gG5OmYXc0pzayPACRP44euxww42ATakuvKZy7T8TptuoThEJOB8N4RQQAk6t03WKkUDBvByh1YRZLIlsUJ18jnMX/wpOfRuKk8CaqEzQZFpQXD8fK11V2Po8RpkOn1a7Vq0uNS/VLQjSn3t8bsER7ETtGdFK0UK8CcAzXt5k5kY0acZ4MiHEiASlEk9MEXFWM8xrGFynQMWjFEYczKeQw5Agl6BII8CRgs/HsqFzqVG8LCFulZWl44b2tWkCwGGzbPCbbiiYFpDDYtH/HXH5VLR3twUQ21SGoeHqXZHvLaHROvo4nwVPE14cUOQLK6KyQPsDLGAyFJrcxqSHy9tDp89kamtXy2DTyYLwAamC5ac4fv6vuP2bO6yLZ8QURFGpKUooUkLmgdg0hKIiTUbUxQrbzQabp/6GY0+/BmeeNe6hrAlMUEZmlkprKua1FAfO0+R7K4fnGQlRA446xvohndN1nDz0DP+c48nGcVqvWgc3pWOZnPyWPrx5mZ3dD4Apqgf4GBmLUImnSbH3WYAW51IgSY9mAdabs13SvICurCBFcEKKDVVVkcoRu9OKY9/+DkjZlYli4VMO3YK2ZgIYVG0POj321f1VpPvOfI3W8hg6792IDc6D0wDsQdOoLydiJXgs/ULE4fPeDjFYk9/hOg+Cs/azaaoeaXOD7xfn9rj5J1fhZEW49Pca3/8tcf4BkmokQlGWCJFZHRjLEn51g/1mxMN6wsqJb3Dpub+Do38F7rggFVBCqlAnub6d1XX0ktkb4kCkM8W7yqqQNW4bb+vT4Nv6EI/Ezv6CIYAn4uPEDnkqehi3hXXTEpz8dxw5O+Pe9f+J3foylatZkWhNk1KkKJToHGiZoWkGGiYCjZnr2mbp2N9S57M0KOBVzSZ2DXMmTP0mnHwRXEGgpyY+gjwNdrcMftWKqw423IKQLNjkvU9jJlSm7Lj2OkqiwReNASZpG3ZuwN4OPPWM4tdB14Q0ArHSt0KiTNpvEtcLs31eb3IuaNLBeKw5M9yALq91qnDV83Ls4j/p7ns3KNMdKlUkOBrxVOURpsFzMDvO+PT3Of/C38PJ8+BWgFWJlGgUCqlsZi2NT3MxIPE98JKsLG+VXcLYmfk9vbZFVxeT6gY3kw8Me3Stb/nnG38aLvdQ48gI9JhMXvqP+vSlc6RPfsqDT37N7tYtauZMfCJyQFd/i4RKzF3HBsHVwcJ0BV0lWTdmDfjSQQA/GTMPB9QKk+OXYPk0UC7EzBfh2vSIqUP3d9c90oX3HoJJH60Plt8lKXv4c5xOwR0ougt3L7N9+Rfs37xMCDVx6Rgnz7/I0rmXlNVTwAroRNAKfGknsbSgydD4KvK9LCJpvtWcCybQoXkOf09CXAVNSfXNf8feh/8JDTNWy0BoEo2sME/LrJ08x7Fnvw8nv28ahiWsK4/NxrdqssPf6Uo/RQUV63vX8eSigBOcpHz4GkPQEelSVSRBKg7dy3Bf/GXGk0md7pzovPk79iy9w8ocdEeRmcHWBw9J13/LvY/eJG5fpeAhhe7hZUrJFKHubNmIgHiLQSi4FO2ZJKN1zMuAOEc5swfSFHO25SwnX/7f4y79R3ArgrOWfqYV8sJLP/12uv0vXOf8d4ffQMYgmg3iykXUrY0Fkn0kDiBtKeEm3PwVD9//Ift3LrPk5lTeaC+uWGZ3HtFywsapSyxfeA1OvAjVWXDmL0Q1FkWrZepokykceLKJoznJ7nc90seZNq2pl1pm4Q5sv6VbV3/M1s13aKYNx868ypEz34KnLgGrQhiDWwIvRHcI3Tv8WZKIg0p2tjze/LU2F933a2Yj5aeeQ82pGMbWQWf5QytUZSEztk2ZOFzg5EmPJyc4ANLkBcwA7GDerTmTNCFRcC4nTKX7sP8JfPwW9z7+LfO9W5Rxi0L3KAmMPCgB1UhKVgTdacKpw+NJTpn6OeNqhO4auharxD13nrP/+H+EpW8JrjJTwaXBfM2WtgPSTEDf/rGrupcPgAFSbQIBXfWeBGguRkjCCgbWwBzSrhLvM3/3J2zf/DX1/XdZdtusjhokHhBzqSUNQlGNoCjZCyXbzQosn+PEhb9ifP4VWD0FsmxaKBbglnO1T3P+C0Jvtung1AceqQI5QAMXgIYU7GDxDbAHuqWwndfgOLAhuMnCtdVDk6A6jJW3UDigOWWwtYY76lMLdLRoYL6GYvEhJFh1U8pFDSaAs3QVVWcHKo+OP0l9huEtfl7BsXe3cZeIOfZtr4DscOeC/63voyiOAEyBBlKjlt05h/17cPNdtj9+k9m993HNbZarGSX7oDVOFMQbrUNtgZJGKvG4ueLG60y1YrrxHTb/6f8AnJXebLA6b5IylV2mXaVRYxPkMleqg8NAQD0q0qUsNFgMqVyA4BtcmKm1NdyCnQ/h/R9x+8Ofs1I1hPkWaGBUCuISIe7htaEqrRh8jEoSB0WFuglBS1KqaFiiWnua9We+D0+/DuVJSGuCG5NKT5/8YCBFEyKFeNoahZoCzh1GBX1/KLTPUQZFvLTGWfknc4CqNQIFIVrgtoSsSawIi+9Y5QyEZshysPm1Y9HvShCirbkIFKOFpmBtVbC2Hko9jxSVxYOsfbAcMr3z+77ogtOqVSVlhezy7RQ9TJ3/pZwHbeZOhGR5/+JK27ApQJiBmyrxIWx/AA8+4O47P6YID5Cwj+MAJ42l6NIgGhmJt6ZPUhBkmXvNCqe+99/As/8dsTguPqt5dQ0JwXem5HwgOK3FkEzSF5AbTxh4EolAgVWHU/Yo2FOYge7BJ+/y8PLPmN9+h3Fzh2V/gKSZdXhzJSFFoiq+UBwNMdSMyjEpQWrNjphIGnAKSSoCaxxwBF1+hrUzLzO68F04ctb8x1SBX5ZaC5w6JNNzOrYCQO6G6jJAYlvXdyZmSqY9WsFZCC8ITPNalLSWVSJpg0rAUSAMzdUhhC8MC0fSXxJoFU3qAZVMPwqpALUM38KRs4fzJdt6FLSBd/uUdr5/SvNsOJ6M4CRADFI24fE4I6Mf8qzb+mrZrEhmMsy1pnCSH2wwoCBzn4gzRebw4CPqj3/F1q23iHtXqPQ+y/6AykVSY7GU6D335yN07WXO/tP/AEuvSs0KldLZ2kppfhLkBxxJWXf0qFjoptk++Do2lL7M7msEapsfD5Tpb4kfvcGdq+9Q79xgRaZMXKRIDYQa5yDEGtUG54XCebu91DqBCY3GnnDO4Qp7JlETMYGUY+bJ+uLMqaj9Kktrz3DswvfgwutQnMJiJyX2zzpRR7WsWJ8fhK2v0tXPHLA1cKZJFaWKmFZHCA4SDUKiou3EkMt9pZEtWAs199vKLjtAJQ8DLJ7+LQpZm8fO5PSdz9SA7ECcKpTgJoIuYbE5qENDVdhh8afWMsPx+QVHyeQqwKW85cwJ725eycG6XOQPo18QxYy7EgI1ZCNPGNRjVrLjOjW7O942TXTzt2x9/Da79z9hfVRQh4b5uITlM5x47p8oL/4XqDwtc0qsN1nI2qXoHpjLCM0jAUHI/k/74GM242po9hTfgO7DwzvsXP4x+7d/igs38HGfkavxNBAaUNfXdZZEIYAo2kRLEJMK70vz3TDBScm0jTrFeY8vC5pmTnKKSER8QWREk1ZpdJMZR1m/+DqrT30Tjp83XygsgV8W/MhMWoZuWuprnLcgSMTiaN7u1oqTOBCX20LOcSiF+hwva0CqLDj52T7COfv9pb06Mz4LuJFfE0IDsYY0MyBJdmiu/Io7tz9mMl5l89JLsHIWGg/lMviJIFZCGXhM1dM/DUjwZAQnj9iiSdo62llQdJRPtDmJiGdiAnIIztLWzqV1M4y9rBpxxIxSNaBzJdXQzKDeon73R9Tzh8wmS6w89Q3Gp18DNqTRMU6cbeS29wbDiPSj99D+YegVeBqIO+DM2efmb9h758fM7l1luZoR623zcURxXq1sVJwjovjCEWPMFWWElBKl8xRFAUlp6pqiKOyslwzV5hbxGoOhbs5lZoGgSUjqEfGW9Ocq5rLMNE1YOfIMa5deh1PfAn8MWIdyXdoA8HC5HwerIxHVPNc2t0KFxUzX/AxwKC0B9dFtIcPrDhG3fMC25r1RZ0o0KC5OoZgCd5T9q6QrP+T+x79Gpw8oJdKkRM0SS0eeYfPS9+DUS1A9BemoUK4/Ook/4XhyqNrQuUzt/p+bORQm4CFkLlaioGjNJXKFjZYSo9lPzAd1GmD25jt1ceRsJeyD3jOnvBwBq0Rdtyh2ssi1CRu0Qbj+jgetDtvTt1uZkN83BXaU+i5c+yW33v8x7F5nVXYZxR2IB3hfZqKnBTpF1OavgZRCp3UUy+dOyfwoL+CcaRkVQSVlQM9ltnjqZpmSIKnAucLmm2pUZqiDqAVarlLrMvvNMrJ0hiNnXzZEbvMcsG6QPBOsP83gNtsTohOMTPG3SoymDqhslQRwsb1LUj7lh9pjODo5awVnARULKI1pmGaWiYlzeHiFvSs/Yvvmz/Hzj1j1e5RphtNAUIeWE2q3zm4zxo3Ps3rqW6y+8PcwPgnFBKQSm+/IzLnHBkbb/fRoYLvdV4//w3Dd/gQlcPv+K3nTa5ui3Acz+/kMNu3jJnwo0YtHXhKwivlK1xWNUf+wWhslc/mHBQnt/yljgC06lXvRMIV0Xzn4mN03/0ea7Suw9zFV2qWiBm2MU+WFpIuUl3bePPLbxafQmYz5azr89LqKmlnbdPHqbPZKk9GwEQmrLKM4oniiqwh+ldpvcvb5v4fz34fiLKQNwS2j4rtaAX64sQfT1Ji6UsD2mT37zoiqxeKtkoVHhtx2Z/5bG8/TBD7Soag8UMJVuPZrDq6+y87DjynSFqXbo9IDXE5ezDMliSNKQSOexIhGRihrjNbPsn7mJTj3CiydA44IugKuGvT0sQ3RshJ6IGuAzA21Yzvc4t61Z/cEBeczj65r0eB3g4fYkhaHgOZwj8UsoIJAkr5u2uHriQUcO4Il5r8UCKQ5pBrcTElb8OBDdj/4MXeuvMGJ5Rkyv4cPOxQuUogjqpDU4VyBalzcPZ9y/N5OdeTNOAyyZtRKpV23FmkKnbmVvJCkIrlVduplZPQ0y8e/zfql161AhlvOFy6M5uPKrJH7HIbOch4WOhEGB+Fg/jlWaWvapgO4rg+BtI5+mgH7ZiE0W8wu/4TZh/9MMb9JCHsUvqF0DS5N0RQzGGOd7lIGPYxdYjlcKpCiI7pVprpGKE6yevoV1p77PmxeBF0GRmIEwYoeyxM0WUFLk2k1KDJJZt5LH8zOm20oOl8MwWnHY6bSagglIF3vNWcQaGsGdHuq6W1zWiqos4ITfiBsuQiIipBo8KkG2VOaO/DJL9m+/C/M7r7DxO2wNArU82k2o0pDvdShMZgzqyDu861hiyotDtcJS+vULzw6LRD15k/mLmpRUg7Ix1zU3gSqLEfsHjRItUIo1kmjM5y4+F248B0oTljPUVm1NYuuLzif59QdQj1NjoxLdzGXBJAipet52AuQeJyD7IE+UO79ht13/5W9W+9QsUehAU1zROd435i/qLVFBL3P+ZHmaw0FByA5pVGLDBYyQdyIWV0xZ5nVY8+zfOabcOlVKI6BrIGsCiwvHkSuXdtFao/SEFPCu9HCwW0YzxdAcIYapV30oelgMwzdd5IX8VEN1ZoTrRnmsh1uF/KqGe7OkX0ahSns3mbv6i+5d+3nsHuVDXef9XIPSXvU9T6umqBSkVxFSM7qkmnqYjmf796xwOcj1+kFB0mdv9P+TVIFeHyy4CtkockQuqoxv0QTmmZUo5JAYBocbnKSvXrCflxl88Jfs/zsf8BvPIMr1wVKYioWOjJ2ptxwCllwAuattDC3b00hzVpKZyAztRjXb7j3wc9IO5cZ17cow30KF8EvUav5OF4CzgUkRTQFNEmuzX1YcNrnrUghpCZkv7EA9YRUUcsSjd9gjzVOXnyN8TPfswZhbhNYFnSSTfkEhe9M4ZgiIppRV5DWRB7st7+44FhntibLiS2Q7zbN0MYfjAWEB9skLZx3yBtV8dT5rPAkCt0D3VHiA7j5HvMPfsLuvfeR+JBCGgqp0bCP05llNnpz5jV/TrtczjnL5FT9HW3Z/9gFaItgtPfTmkTZ28523KI5l9uRaJEd9RoRBTUfwLVd8QxWQEStZX3pmMaGIBVSTpjHgunoNLeaSzz14j9y5tnX0HJDaibogPnR5csMTzfptU0kZP0uEBuKVIObK3Eb6pvwwc94+MmviDsfM3J7+LSP0FA4aGIEChK2WYsi4VxCNKIx5QMgh14X2A4WaBVVqKdGWXIl8yZXpKhGOFfQWCCMWVNQs8Jo4zybF16Dcy/D+BTIOrjjolISqQ3JzUeA4EhNpCw8XWxRbCf9xQUHEm1ntjbh2B1Gu9IgpgMd2U9zYSfPgPKRsKctrXPdOqIHikwhbcO1X3D73Z/Ag49YczuU6R6a9sA7fFHkbWBmoaSI0z4q0cYFDAWz2cthOOnTDHUmBPZhg7yk/HlCrs/cj+71rU6QvkObzw9csuCoKuId85gIzhH9iODG1Foio1UmR59n7dn/AEe/Cf6oqC4xjwVSlF28Z4HEmX0esxKK/NQai3HpXI3Muwd7Nwgf/Iy7V99gKd7HN/eoOLCDSS0ULdZqGyc+hyIMyk9a272I+ZApDv24dpjgeLV4F/PavNXRiCiOeTNDU6AqxLiNUuCKZQ4Ys9OsEKujHD33IpMLr8H6C+DX8uUrUa1QGSM5WG77MFsyXxjBGZoAjq7JU/4x29cuKxJHl0fvUt9tWnuhGlYrEgLEB4rbhv0P4frPuX/tl9Rb11nyDZUHne6yVAmEOVGUKIkg0kGyEhOVK43Okp1GRYkokUgSaDnLn2WIslCEpE3cG8qitn1K5VCAUk1Dd09QMzFIrBiGqjXWijgaP6Lxaxywzqw8xYlzr7H63N/A6CS4CTARwghS2S+8hybNbGOyaOO3RqpHIe4D+xbjuvMb9j78Idu33sY391gpI6mZsTQeEUJAY0NVFWia09QHlFVBCCYg3oshcimYJqfVmgYrtwdGbx5nkzzmmTlvvqgqeCidtWVJMTCfz0kKxXgZ9SNmjRCTENw65frTbJ5+GZ7+LqycAzlmZpwfgcu1+BYcvC+K4AxbhDpT/e3h5toF0zQ48cimQl6wkKvGCNnxj6D7EO4qu9fZev8HzO+8je58yHJxwNjVkOshO+egntmmdAXqPEETzhWIiF0qWmlXlynrSU3XpfxgiIcry3y60ZthmX5z6GIqQ3W6aLZp7npt5ZlMuETMcIqMqKmY6wSZHKOpTnL6ub9Cnvlr4ATEI2Kpznltw+BEbwOVPmXOBQPQPmAF6qeK7kOzBx++yc0rP6XZucoyd5m47ZweEnBSUDc9uBJTQ+EU7wKxCfhcXiqlfH+eHIT1Zh4nWxvJ5ntnjaCm+SlyINXMUiCz6e163jmkLSQTY1c72zmD7msdM4urJHealWMvsXzxe3D6BfBLkAooJ8IA7v9iCA70GicLRAtnCgPK+ALa0b9FMVMiNHPKogbZVsIduPZTdq78lPrhFcZpm0qnGZVrzaEWlYmom1vAMZX4VCDJCvD12yiYGSEhs7uhDVKCw6XPrnEWETVnwqptpmfWvFKi6knR45xDJBHiDGRONSpo6mibShLOlyRXcdAUzFglVCc5cvY7LF94HY5eAl03ZEkmPcDioK3x1sHNea1jNH5d0oSjssLq6QC4p+z+lnTtp9z94JdUaQ/RGsccpzM8c3xLsep8z7xmg5PBKQumcBr8WbtVbWMn3bToBadFXs0f7OoRDD5jGJxtwZiFwylFRDwwptYlapYpV86yfv41OPMyrF0AWQW3JFCScF8MwQmRjgbfLwqQXV9N0tkJGs048S3kEfahzJmV87vsf/gGD6/9DL9/neX0gEnao1AjKSZxpJyxaJ9l2aahyL5S8rhU4lLRm0+SssDkugiSOse7f6CfXd8oEB1dXTmHIMk2sWTmX4oe7yakUBoFxydcmUi6TyBQUOHLJQITpk3FNE1wy6c4euElyqdfyUjSMWBDSGOQTKFpnX0FJJIIhsqlAu98ttiCtTJ0yXhqYVe5+wE7l/+V7Ts/Z0XuM9EtCm36FoutST08pGRw3OUU+JQzWIuU6AXLvrbPaLi0bfldE6DWB8yvP/y6wVcGApgkBz6lPbASFck0aIrWrIwxjawyd0c5cMdYOfUtNp75Ljz1DZAVSBP5iwtOa6m18TPLu8qOvZiLHq0SFzHBxIFogDgF9hW5Dw9/zezDn3H3o7cpwx4r1RyvB6R6hmqkyFR7p2SIli4GYw55vwZtWrYCw1hBd/qrOeednzF43We+fwdtuSOf2jnmnCVVNHm8q0DMpFFn9QuSmI2qePbrZfbSaUZHX+L4M9/HnX0RltZo+XlQCjoGHdMCLTGCKyCp4r10mjzRgwLCFOI9Jd2Faz/h3js/IOxeZ8lN8TSGPsosC3mL5g3WhuHmz6ZY/qlnTrS6PQuOHtIIHdI4XGc9JBguPwftnmsfXhtUMshwfbvmAIU4Uoj4zBUULWiCEpIj+RFzWebAr+HWnuXYhb9mcu57X4z+cRmose+l/R+QN1MdGyrvGbkG2M9w8j345Lc8vP5LZg9+TRUfsJHmjInIfE6MgaIoKEdjpk2OMmewzdM2impN+S73E5cnEnO26NCMsuh1W43fdZVHzbz47MLjMv9OUjRtqqbFREuGxL1GpxnJKml0QoyemMbUboWjF77N5vm/gWMvgjsluDWSOqIY6mW1rouMDgk4wfvWUrOb1NjgNOBdY3By2IODO0yvv8WDaz+Fnbc5Mt5lPNpB630kjSzHqmiyPZQvnXy3biIezSCK3at2/ZJt47cC25oUvVnW9+ThEaEB0DaVPvs+rZnX8v2i9P6QvUZJagCET2byKo66CYxGI0QTTW11ycfjJZLzHDSR0tszmR/ss7P1kMmp5gtgqungH1biCUCTs5KrQFEmLJ33nnJwhfjRT7l35Wfo3scsuzlaH1ibcIVQz/GaKEorLBvrGqkKQg4O2gMUnBou5JNpjw41A9rTq8347NU6JjCY1mmL7CQXPpfgCLa5BEsLFy0sS1VHXY+ZIHNimaAcMw/LzJoVlpYvsnbyJdyzr8HKaeuhykRgREpj8N4i951tGkCNUApiWf3JzuMi5d2sO0q6BQ/fZn7159z/+G2qOMM125T+gJIZGvYZFyUi68T5nFQeZECmAvVIG6gUIUkiSUMbmPbJtLZPzlqKiOsCt4d9mUVhaUGTFiGyZyEYJA2J2F1r0b/x2h5GvUAqYr4OIJWlpbgY8YUJ4UFwNKzRVKdJS89w5pv/AE+/grEPlr8grX6Hujs04CSXSk2QptDsKA8/ZP/jN9j65Be42TWW3S5jt0+qp4zHq9TTA5oEo6K0LMhQgyb8qEBTytmU0Br1SQbVYMjnmpDVe1qcmvZQbOp8nJQbVw1JqJ9xZH5dW8JQJaEukTSRpGIaI375GFMVdueeydpFnrrwKpz+DkzOgTsh+DEQzIl3ZVdYPeV05xQwWNmZyFitAgEXgBkwVeptuPUW9z/8V6Z3fsskPeCIn1OkSFFB0jlRa/zI0dSKNFPKpQkxzmkNOxn6Gxq7AKz2t0rb+UCcOwSOtNplYXHaix1y8h1tW8reWSMHvnrTtzU8W+i8pxEZ7pgQmtmUiIdyBS2WOGiEWbnC5tmXmVz8G9j8hvmIuiTGuq6+ABoHLGrcxkI0YNmVu8rBDdi/xt47/wth+wpx7xMmUjP2iqZAjJqVVcR7yXZ6JKV4KIHp9zvvPb08ZX/GvrdvXT6psibsTr3ePGvrvX3m0bZWzGAFJLPBXUFgQig22W3WGG18g1Mv/J3lobhliB6KFbHENStGol0JDyFqQdFuLqUnbKa5aQgCxC1l9jFc+wk3r/6YZvcaS7rPWiGUKqS6RlwEaZjFPfDKeLREDI5mphTVqDOzXKb4ONEctF3U2ouomlsAEYbVORdY49KjbbbmwmJJZIyONAgeD4V0+AzbNbZvMsKKw7sxM52wF9cIozMcPf86o+f+yhLm4gTK5Q6OTqrZx9X+NFjcXgMpZkFBPubBL17g8aKYWOR1taiUcYyMYh6AA2V2h3DtTe5/9DPq+++yJluMdY9SZzhtj52C5KocwVfUhRw4i3YQdSZfDlB2wbPhY3DdQ20RFshxk4ze9GDA4HaFbMqlwd/NYxrmeDzCmB4gdcOVEjWeVFKlcY7oHUEqaj+mdqscO/MKyxe/D2vfBI5BMxFGS51549v8AGwdJG8IK37vu/uw/KI9YE/hAO5/ws71X7J1/Q3K+mNKf4/lck4Z50itSJoADucDURtcZYzsukngKkpXMqujddfDWWliyVqmLcFF77+otP5MwQIKRrAnkX/ZQutD9Kxdd/uNAR6HBdZe0wqGdkLaCg/dq13OjPUEGTFtVlg+epG1c68Y/Lx0EeSIICuo8waYKJbBS+uT62KmQb+xesHRhZ/6jbGQQdjelOTiczk+ILTI5xyf8xDtPMz58ak2SJltZe8jDt7/Ads3f8ko3WOkO+hsi7Hr/Qo7bVJ3UiXpazcPN+pQeP8gWNyhOIuUDmGA0uQrtXEc00xWUKMSIHrU2HD2zhQQF/He5SBfQQzGbfOFoBqIzKiKEdoUJBkRypKpLLHHCrL6NCcuvM7ome9CeRRYwoiJFZp9CMkNfyUN521pEzijXdozTaBT0IdW3+2TX3Pwwc+Y3buC1128myEyxzFHCEaGVei7ArUxk8GBI6aFh3ER8xdZOGT6ZzII7Hacs3bemRVx6Dmk/H5rwJAgGitAxeW4C6SUEDUgyElJSBZAT5Lw+bN9gtgkC3qWK9Q6Yj8swfgkbu0ix176j7D+NIzWQCpLs/AjrLJsv4GG+0jSwFQbWCELNz1A4PPtHsp3ycXgwCF+oCoZylSwFGRrIgHNVI3OXcONd9m58nO2b73NWO6x5B4gs9t4nTEaj9FGUEoSlQXFxMwMkVxfayDyn2t08Zl2PYYPfXDydSuZO8gl7R+oK2zTakSTRa+roiTWibI0ImLTzHCF4ErYmwbK0TF264raL7F04iJHnnkVTn8byqcAo8HHLpuxbyIvQAqKG3Z78NDVfKPBuGP7ysFN4vVfcvfDN4hbH7Dm9ljxB6Swhzp5hK3wRy+ZaF/fOweOpVvHHhHT/LVd555v187XnqPKoRoFknLqfMbenAmNHc7G5Cic0jQNKQp4Z4ImaqnszjGvI8VonUYn7MxKdHKSk+deobzwKqxfgnRSqDb7exqY+b+rZoGoRrqSinqIPp3VhU152H49F8JO7d8FMjRotYZSV52xaUyVtxsM3QWXkZuPfsYnl3+CTm/h0y5FmFJRM2ZOScClmD/VWh3GFj2XBNIiUMDnEpw+0NjHIXxvR7fatyOMmuZzKohW9nrnCBJIzIlSg0+5n6jDaZlLL2T6CI7kHI1ClIJQrbHjjnLimddYuvhXsPo0yAawJMgYy2bNxcnJyLRGa3wrlZXayn2AAeqmttjKaKroPdi/xu6b/5n63hXS3h2WijmVC4SwR3SBUenROnyOY0dRV+dvXRacFt4fmPpDaJkhHqSDA9oyMhdSsgmIKqKNsSqcI6qnSRkAcI7SJVIwVof33mrvxYTGRJCSWbnKVlpFjnyTU8/+LeVT34ZiE2IFxZIgy7QNfP/YSjkDwQGGLGO7k97WOiQ43d+xhKUQ1ZKYXF6glDeawwQpRWBf2btBfeWn3P3op+j0OqPiIaSHlK6hVKFSj1fBqaAp0WgCb06lcfk0BzJb/2NhRp9htHTFbIwOBKcPqvWCIyScWs6HSwWKpybhCqAIJKmtp0xSJDpInsJVFH5MSJ6aitqvME9jRusnOHLuRTj/XZicBjkKrInqBFyBqqFhhV+Ybn9OaO4EUARoMiTsa4UduPUWdy7/K/s3f8NmuY+v79vB5A2ObjRSi52mI318Ncw/dv1MY/TGvGhfEEUHV07Z82+Ry0UKTatx6H0dTLC8qK0nFqxVLE6kLjPnmjllWeKcETdjKEgyBrfCzK9RHjvL2jOvGYnTnwI2hbb2URMpylFXQrera/0HRkbVWkh18U2Lplt6BASwh+cW3hBCMHauU0gNxB1FtuDub9n74Ads3fw1fn6ftSWhFKGZPWS8PCM0+2jtKGWMlxExmOmj3oKRsY3eS8oxF4ePfemlzzN6rXX4fnpT7VEn1TS05npt4to/uJbYb8ujSkyJGSWNX2VeHkdXL3Ly0t9QPP1dcBvgRgZzqtnV7Vom7GOdYGH+NiIvEJK91AFe7yk8hPlN4tVfcvfaLwhb1xnpHmOZE+d7TMae0ishNqhGSiu2ZhaB+3yoYG/FLqKNBro8biNmJI2EpCIHeh3qrMhhu+7SAi/JUg9Ma1sVHlMQiSZFfFkxndeYq3CEaTzKvHiK1af/itVLr8LmGYwBXogV8ihJ6kjO1qArl3Vo/L7SUguo2mFPBg4JzzDG0TYLApp5oqwcSGNQJzVwoOzfgXuXufnOP5N2rzDmNmvjGh8OqKcHuFRSjTx1s0019iATaITYiOXye+OqBWmIrs/r98nhkp34NpdhHstnHIf8G7v3Rai0jTd0AEE25YrSG2W+ARGPkwpNBUELGleg5TIzGbP81EXWnvtri+5zHDgukQlttVNpIeO81P0zS6ZaElmKElh0H9IDZf8Tdt//EXeu/YpRuMtGcUCVdnFhhneKlBWhnhNihEKQpIQQKHBUVUVIn33tRF33HJIkkGAoZw4g2+hjLIude1IGfAzq7Xyz7PN0OUXJ4cTqBXThE6coDXUU5m6CG62TWILqBEee/h5y6e9gdB7SilAsDRbWyu2q84TMdK9kkaT7x5hrotp2/B2eqnayDSswdl7EIazZmKkJxx6SZopuw+41uPIztm78gmb6MZXsW80sjbgU8Qmq0hCfFAKurGhCNMvOGYQayfW9nBIkDiBih0+SEZyc6vq5IvdZ47anoxpNva32aY2sWBCeHsI286TdOE4i4h11LJjFJWJ5ijg5w5FzL1M9+x1Y2gDGKEtYT5kRntJ8rA56LYfTMniyJfFphHoHyuy/3H2TrXd/yP7t91l2DV4CKRzgY+aRSTQfIplTbQUrBHJNtpQSKRnt9bOaapIK8+PUWV9WqTtCbLc+6jpt/CgrQLtwgM9RaPvaH2JJIKmQnAfnieoIURFfIeUG++kIxfozbJ5/BXf+21AeA50IFKZphklwOZtX2pYk0gsK9FrmD/k4hU21vQlZEAzB1rl1i9ufDd5MoIroFO92FN2Ce9fZ+vANDm78lqq5ydjdZaS7lN6QF5ER4qz4QtSUA36JWa0UfoyrnJVa0mSfq5bU5Fy78Ll4a8dnejR35dOOxRhOq2VT50No60sswNWJtuiiYuhOkorGeYJOmPsViiPnOXbxr+CZV0E2IU3QTIfJBhYFRi6Urh6s5IcoXZF6W/k56NRiL9xFP/glty7/iLD9PhvVPkd1H9/MrVChc0ihOHyHdlrVf6O3hAQx2bqpd7aB4rDp4mccLRsaBs/ELQY2UxuwtDhNCzdrBnraYvBpsM5IQjw0IViGp19inpaZ64hq6SijtbOcev5vYOMiVCfArck8ebwbZ39UERxd5RBnX1RjB2IMheSwwMQY+2qsw9ttfZwQAt5XWatk2yELiDpPkratRKBiiqPG2ljcgys/YvrJb3hw7ype95kUAccBEmbW9177E9sWY6iuIVHSpgib498GBm3J9RETqo0Wa37/54BTgVja6SvBHFePzwlRVkq+AXyRE5kClOKMrx0boip1OWafJUJxhuWTL7N68W/h5DfALaGhQIqcCKUFpEGLi+yyRK2hMLh5GDPzNAi7oFvKg/dprv6QnVu/Qfc/odQpXhSvgULnSG7X28O+Q5Zwayq1gcO8+rm6y+c5e4YZrClrmvYwagOPLnkkDYPQPiOjgjglpTprFW8kTF/k2M2cmHJRx2qZeVphN67hVi9x4sL3KJ/+LqycMhNfJoKOGFZr7SykhRCLldACR8za/bNgstIWm2irKqWoOC/0dbRaqLBBqXEyU9iC6S1mH77J9rVfUu5eoYxbIA3iAo5g1fYRCl9lddUiV+2GT53j2N1Xjha3qrpHzBYZDI82tP3scLRigEZRFBTeQ1I0hh5hKUwoA0JQtc2vJTF4Ci2Q8RoH5QpHzn0bd/77sPosuBPAkiRX0bbhEDKreqGHBa2EmKmpSkozvG+AqdI8gIcfcf2tH1BNr1McXKGKdxhxYA2KdZKLWbRxmx72HdT56FgN0G9yGPpsn8c/7AVUc7wm5cBsm+Dnk8NJkdc2Q/qF8RvmoWFUtoJXkJwnJLGST+Jx5ZigFXMmTDYusHHxdXjqO1CegLQGbknUjbDcnmF2aPZZD7kWwxYkMb/mMwlOUiU0duAJoKFGCpP8Rh2Fz7WTdQfiHeXeb5ld/TFbt39LqB8wcTP8fMqkcEZJUCWFBp+Dg1YS1liyKq0/0UaG83QHSU7DfJfer3C0m0Gh45N1h/bnyMAUdRRaGgJIILrQlve33KaUnX8NxrAuVpimNeZyhJWN59g48wpy4VWzq90EGAmppO3jqQJ1tptbZN5aV9gPcT7HV2OIs1w3ecsKy3/0Sx58+HMO7n9ogsIBhcwopMaJ4JMgTYGqZMHLxQglZE2CCXm3gbVb8aHPAS4/m8/uI0ouza7S+sV26reMc5ey1dGmexKJGlDvcIWZ7k1jweyinBD9hFmomOk6tT/B0adfZenpl+G4aXFiAWWZH3kJuSqPtLXKgfZE6gvn98LxKEPm03OdO8pN00DlE64l/7XpZc2BNXr95Ndsf/gT5g/fwYfbVH4X5+eWiRkVnxwa7dQscYj3oBENOdlKctvXDsodBseyFtKW6OkOCULKSE3+qUO17Bdl/Kz6Jp+GoUWqIuqys4pDpMBKCyXceIUZY2Z+ndWT32Dl4utw9DnTLu64KJOsnNtHlEAcTUxI4YYhVjyQwpRSGnDJfAzdVfauU19/g62P3kD3PmaiW4yYUlWKajCEUZOhTFrg1WraRCSvYd2RRJNLKMXCWna1qLU/oNq048/uK5rgaA5NtLQjcJnKn/CiaGpsC/tEFAjYV3UebRy+nOD8iGlw7DcT/MoZTl54HTn3Kiw9A+6IwCpWcRRsjzaEmCj8cp5LZqW02gahB7j6/dbGAQHaDtefdoiq2fE5vIQwx4U9xe3B3jW49iv2rrwB89vQ7FAWNUWlJJ0RmgNCipCrwFi0XJFk7p0FV9sIfBsUc32WY+vjSE/YW8wWbAOPPfJlJyQ5bLmYNflZR1F4Uoi4mIsNYkX2gnPM3QrzYpMwOsPy8VesM9rR8yAjiA2UyxJ0AjLOZZSskJ6IZNq8Yx6NiuQxjVNKBJmC7lt9t1vvkK6/wYObv6EI91lyU1zYQ2LAlxBikw8dQ8SkRd4ybNuneqcOEk6ur5HQFWVUK2jhVXGa25FgRT3arjmffgzo/i1ZNVsU9lwC3gVEEyE1Zh5WFZQj5hFm88ioWGZae2ZujfHRZznxzOvI069AdRxYt8zV6EEKswYE5jGBE7wIuZ2QaduBbmlFp9dCh/q1wmc+cQtrD1iDztR6V05h+gm77/6Q3Ws/ZS09oAr38XoABGJQ5o2xCEpfMKpGpqhThm6zRxZyawtxLdbQO2xtCYGW0SpquefDvIyh6dAuQ083z9BmF6lOn3kBVJT9+gDnCopyjJMJdSioKYjVMnFynBPPvg6nXoGl57Bi3mODdstcjWdYiVOkK6eUEoQUGRV57nEGug9+X9Ed0vXfcvODn+Ievm/1EcI2hG1ErF0fzqFNxJe5s7M6RFriYe6jo5qRzyIXvcjaUhM+axRBOhq+qKNNcz4Muny2Yc6xJYAuXk+zEIMJjTqPL0ZMU8nBriP6JYrxJtthwvFLL3Dywiuwcd78F1kHWRXVAnG+e76hacB5iiIDKQsosNV5+51xyaFvKf0h/Vm2jmjchbRlOeU33+bB5Z9Qb39AEe7jdZdxESFTSFBHkXu1CAliroHli9xxzJKWfC69g1in5Bhzk6bBDFtUrM11aRPNVJQ4XP/8N1kwOfo/t1Dy5yEpSiE0KszTMgdplehPMjn6PMcvvg5nXgRdAr9qTXgpULUC5R2In5HA1FGXTKi722gacHvAA6X5BK7+kJvv/5Swc4PVpYDTfYhzSgqqosSlSGimkBqrC4Zx9TT53umXYNd3an7OIw/WDpceUTsEAeevn3/0ZYBVy0zSbMXX6n0XXgghoVKBW+MgLjHXVSZrZxgff57q+X+A5dNYMl6ZG0WVtD6KkTnhd4ZWBtGUNqLS4rULhORWGS3k7Rx2C/64Ido8ZPruf9ad6z9lvn2ZibvHhPsUsmN5GDEiMrabSNbfpSDT8bSvIGmsVCvVF1PqHqYqxhhmGC8ZAq8DdBrXaZpW3bssbS3rtoUVhis2FLShE9gnSvXL1MPb9oCDlNR+if00QibHOH7224wufA9WLwHHIE5y5NmRqDsqf8SZoy/951kxRdfNwSf6YuMP3tfdKz9g6+Of4GbXWRvtM3EzYtjLVS0LhDEaHJLZwE6sRyqAExNWVem6b1ugbhFJs4kYS9l3pEtnNmKGii0du41Nge9iaosrxWAt22e0+JosIHkPqPShgzTwW5sAxWiDOq5wEFaYbFxi49J34fRzVobWnxb8klUwymnd7WeJtLEyCw4YyNJOpp3pITNTDt3DI8haz8a2l396zVvs3b2hd6/+hmL/I3zapqhmOBeJdY3WkaqqiHWize2Alk6haA6COi1xAqoth9rwbSelLUHWpz7j+obsGMITXSI4jJKvGOYPFF2OSevjxP7EpLWpsykiub6zWvJSIVafzAr1Ye6z005UQ4QoJSITDtxxdlee5+gzr7Jx7gUYbUJahjQR/AqUOeosiwvsyb9W6OquUXZoswO8HIDc1w//f/9PZPsyVf0RG/4BvtqHsEeUgPf5ZFU1tKyAlIQYrBlWVfjciCrREh29eNR7UrS6Z6WTfND0iWJkf9C3SWHdzNv2GMnOFaWLsyVylH7AL3MKkhSSWgNggXluPy2llasqYmyN8Kx9Il6EKI7GTahlnd10nKWj3+L0s38NJ79pJWcphWJMm10pj+7/7qvk+1n4S3dQDL4/9N5Hf+iv81kEprukzm4r3ICH71J/9Btuf/QWTG+wPg6MfEOa7zHKkGFKLbyct2AbgIwCyfIfvLdNm1BSa4B2K9InOhnmbgGz4MjFwjFkbQFV66lAvUUiCyeed2Ka0ZV474lRmc/neIHxpEIEDqY1USr8eIOGVeZMWNt8mvHZb8OFv4PiOAYlV6AVZpYx+Nxey/Wdm9sXhHzKFZ2xZmSAPdAtZXaL9OHPuHv1Z4Sda0zcLktVg6Qp9Xyf0lnAVTNnrMitDlOKNE3TMXb7HBG7d+es1nWq5xkwGdYLo4ODvfaafdhXRvMvXWpXsi+fNBweq7LpFMusdUZ/SVgezNiXViBdsDgMBY1WxGKNUBzl6OmXqZ55DY48DxyBOBaqDdN60c6mzwzq/YWGaNd9bKpoDbN78NGb3L78Q+LOe6yNd2H+gNI1eCm60902aoSiRMoRGhRfkyFI61imBUhZUQchOtchGkaFMBhQFIqMipnm6blLLi0uZ/djpqZbCSUlhn2qqiLpiCaAcwXVyIPOmc5mJHUwOspMN5m646yc+jYbz38Pjp2jz8UYCVSgVl0mT7SrPfZ7BQfyLkyD13WzNnPNN8CWcvO33P/gh8zv/pal5h5jdvEypcz9HzUEQpPNs7LAFZ46RRIJdWJNrWIkhoBP4H1B2wenRSG165w2jGm05m6fStwKUnR2gIkWtBV/es1kPVhxRrx1zsIO8+kML8poPCE1DRQV0ZXs64RdPYJbucSpi3+Pf+Y1KI6CK6XVglaydoRS2n75skkNII0mDkJgXJRW0TAeQNpWuA+336L+6A12772P1veRZp+xj4wKwaU5McyJsSF6I2ZXWuEVXMbYVVIuyVTl08zlmG4+AVOBV0cZ2wduDzF1p+YwUNeOQ7QcEkVpG05TiVKR1FOnhPoKyglzt0yxfIb1s6/C+ddgfAZkw9p++yIXN5SsZUqIuSmSZ8GH6Hyybj6G1CTomc1dOwgByW3TsWKKBQd4t6+kO9Dcgcs/4f4Hv0DCPdL8AYU2LFVC6QwciDHgCst2tPUz8qHzGAcr1rZQOTu0J+q2MH4b72rXLiNvqS2HZQISfJMFx3VJeoCZ4wKJSFmW1HWgnjeMRyOqagSN0kSo/ZidxkG1zpEz32J88W/h2EsgT4GuCcXIIiwy76oFWOJF9Rld87/8kKiJjhurdc7TNuo1KYBOlfk9uPUbbl/7MbP77zNq7rLEARNJlM4i1gkLalnB8tymPAZC3VAWVonTBKfDxhYeXqeFJHY2eJQWMpXMinadmZcGJ6uXglBb+whXjYmywkFapimeIi2f5fQLfwsnLsHyCWBZNBYgE4TWHMsbLfn++GuXZACRt2ajHZ29Bm2Dm93p2WqfAcoTyZ2ztUHigRoVPIHuwu3fsHfzLR7ceBs3v8WEh4z1gCLNcicEq+IZk9DEiLiELyLe1aQUOwStrckA/WHT0WCGUKQOBQckH3J9qauWrpKROVpOmfWOcX7ErI6ExtGMj7AzOc3m+e+yfu41WLsI6QikkVCOwZU0mjKo0k2grc3arhyPaPAv+BBrmiR5v1hSVrtwkgQNSsEc/D5wS3nwHuHqL9i++Q5p/wEVB1Rxj7KIpKIhakNQa0jrxRsCknqYVhk85DzaLEsBo8Hn3w2pOW6IEHUnakRFaFJFUSyRXME0VaTqKKunXqI6/zocewHcJrhlSVQEHM4qimXUiwFE6brNDhmBh9wQ+3cIjvT0s3Zvdnc2SISLmnAy0FTtx+gMeKiwBbO7hI/e5N61nzHfsjJNy6WiswMqZxs4xojSIM4KGCZi13qwT1u2Q6mFhVX6npnDMfSBWu3SIpQWN+pDASkBUhHdhLlOqBmzsnmW5bMvwcXvwfgp0E2Iubt1Xp7eaEzEJll1VUBTQlzIJ82XUHBiNIpG64DGHIuRNrDVbpIQoKnNVpdtpb5H/OS33P/4V+jdy4z0PpU7oHRTRBtiCkQFV3hawqjPLcf7RUqos8Qnc259fl02fegLCVo3Zdehb14TXhORiplfZT+tIqvnOHL2Faqz34EjZ8GtYL5LCertX5dbbpukY/QPRkpZEDqUpxXsHtIeapxWQIaht0c6LQzeqvmrgdcJCYGWwwVTozhtX2Xrwx9z99obHK128PVtyrBLJZFCygx/GR9u5madqWWm2KIP1gpOey8ZYhjkHNmTjlIQW+GWgDWMSmgS1C1Ts8lUjlIceY7Ni9+Dp57P0f0N637QnjrSF7avo/nDo6qk54gN16Q1a/lSjT51eiHrre24FbPjWZrdq5hdIjX4Gciuku7Dg/eJ197k7kdvI/MHTNwUrweIzvHOTshh/bEuzt5mCyLZPLNSR+3D7OILQBRnHcWkJGmFUiKppJFl/MYFNi69CudfBXfMeE2yQrTajdaXsp2/OtrsVbPfbd+7wYMbxhNtdrZG0uGerSnTvir0Wir/vTV/W2U1dIA10VUD0rx5OSS8sAN6V4m3CJf/lb3bb3Hw4DKTuM9YwDcNEsB7oS7mVk9Ney1i2uwxkXzygdTek9qBZeVgiy5Q3XLYIhWJJYI/wsZTL1M899ewcQn8BsiK+Ympsvn7vJjdEVIwZIJ12So5MLmwnF+yYYLTnYaLqFAfKOyHnRr5dRpB5sCuojOY7aEfv8eDKz8nPHifSbzJkrN+mjAnOUG8JWvFaKeZk4okZT6hLbDntBXgbGo4oQ4NSUakcpW9uMKsOMqRp15i/dyrcOrbICsgpSDm4GuODdDOV1u7rB2W2NX5Ao9dnsVAa7/3B9WAdPg612mUR8yigXeHuv69rR8kC5Zdfh65vJPsK2zDgw/YvfpLdm/+Gr9/g2XdZuxmJJ0hj1CUWGBBu6KgmTcYoUNJGi0ukyBqDtq6BAhBSwIrNHKSeXGa0y/8ezj5AmycBT8RC1T7Li4vcZxVdM516YCJklZ4+nWgzdlbXLcv2ThUAndwizrYBI/5u+vgTGhyt2CvCinnwT+4DFd/ytYnb8HsAZWfIe6AmA4QplTOejyShKCWB+Nz+dR2R1lNSqtY0vgxNSuk8XE2nv421aXvwsrTIEeAE6It8fHQY7KTN/++60jdPqhhGaP298P3L0LLvQ4ZOAKPkbghi9vecaiKaevE5w3UWXykXisOgnopgfMBKzx/X5leh7tvs3/lFzy88S6rVYNwgNeGUhJOawhzXObNaXSERhFfUIxGxFgTNeB9Jma7JaJ4xBU0OmaelqhWz7P+zN/Cxe9DvQ6j40IxJgqZGmqjhJ6H6xZrBlhhDL8QF+qERhm87jHw/hd85IKEA5i13QjDaGynfoc9B62WyxAbcURI86yjcjPVegc++g1bN37F7p03qeJtlv2ekUZjwrvejCnUCnGTovHb3JhQrLIVjyAbl9i88H0rIjc6ClpYydByRZSVPrUb6O34wQbv7rj9pj/ef5fgLPo07fWGgc/Dq/m4j0qP0UpuIZ/NZ05X/5q2xfzAj1KFMAfm4OdGyI27MLvH1lv/mfmD96l3brKku6y5PYrcIY1cR4FyTNSCeUz40hHTnCbMGE1WaMIq2/OKWJ1i8+nvsHrxb+DYRdPiWgk+c8eS633E4Up1B0S79ocOKB2u3+HncOj3X5LxhwWnK8Q3dH09be93BWZBKQsZnKqDrDptIO0C95WdD+Daz3nwyVuk2W1reacHjGWGxJqoHqSiUUdgQjE5il95muVv/hdw4pvgToKuSRNKilHVzbvtBWpbLS3Mo9147dwXTaiEe6ymsXdId9V8rccGPbuVxHyboeC1QjM4haQ9bNreBImKSF8Usf0sW+fuHoYyLGYmqyjCgSUY1vfg9mUefvgG8wfvsyy7jHSXMH3I0qhif3pANVqmEc8sQbW8xjwFdqfC0pHnOHHuVbjwGoxOG5wsy0JhCWKJxrpvS0GbHEfK8jBA4vpnYPclA0xtQYhaAKJXtV+60YEDiyYMtNBrLzCW2dfSLAcWVT5Q7NRUDAbrg4QKLkIzBwmKNBAeED9+izsf/5zw8DLL02sslZHGjdiJI+LSUxw98wrL53NcgHXLJ48eypGd2JpTlly7pYfVKHXxlFuAvnOfnO6vdleHOxn3448xI4br175/0cjt17AFD9prt3W9fv/nWyPYXN518EpPMLg/zMDVit+HB5e58+HPmN76NUvNLZbifcqwT+GFRisO3AZ7soKsn+HsN/8eTn0HimM2k1SAa5vFemJI1jNmeABEoO0Q0yrG37suvW5dMJ+/hALTjoHgHB6LDz3lB9g5d+0fAMXg1N75XQwiDjeKxgYnTUbk7sHuVfjwJ9y6/h4zqbjw4uvwzHdAjtnJVx6V0BT4QWwSzHJpeaBG8G9Pt+HTOHSyDQR9aEwsFqR73Mb9/UOHjj/Q12uwv7aY3PB6i1ft9V5n3j3m84ebU5VcngOyT5/vrUHYB7bMF7r3Hrvv/ZB65zZhfkBixNKJZ1l/8W/h5PMQ16E4JYnJwixt+p4FyF2xoHhOqKNlXXewfS9Bi5kOLTn30Xv/ssrOQrcCYFEw8jic7tGdjt3rsjmU6MoaKRA00TQNo2pEIgwywEMuSeSAGmRPbbMUkDJvLNvVmqyE0cKUtM8BIcUOXrbJuQF21p/oixdIv9/GfvzxOVyAx4/f875Hk6YCrSS3PU47AT50nSZYiaI2KVBSyu3MpUcLxXdmYNKAl4hxEPcUpvDwFvPtLUabx2HtBLAMOpG+7li+Xn52EfssK9PVz22hSCKD8kmHMyt/x/0/bnwZhef/D4onBJ8FtKHHAAAAAElFTkSuQmCC"

# Todas as empresas do grupo monitoradas. Cada uma tem suas próprias
# credenciais (App Key/Secret) e sua própria lista de contas bancárias e
# cartões. Empresas cujas credenciais ainda não foram configuradas nos
# GitHub Secrets simplesmente não entram na busca (nenhum erro é gerado).
EMPRESAS = []

# --- Prime Sol Matriz (já configurada e em uso) ---
_key, _secret = _credenciais("OMIE_APP_KEY", "OMIE_APP_SECRET")
if _key and _secret:
    EMPRESAS.append({
        "id": "matriz",
        "nome": "Prime Sol Matriz",
        "app_key": _key,
        "app_secret": _secret,
        "contas": [
            {"id": "sicoob_matriz", "nome": "Sicoob Matriz", "tipo": "banco", "nCodCC": 11213271714},
            {"id": "itau_unibanco", "nome": "Itaú Unibanco", "tipo": "banco", "nCodCC": 11214288866},
            {"id": "santander", "nome": "Santander", "tipo": "banco", "nCodCC": 11236843385},
            {"id": "sicredi", "nome": "Sicredi", "tipo": "banco", "nCodCC": 11239054225},
            {"id": "bradesco", "nome": "Bradesco", "tipo": "banco", "nCodCC": 11431467344},
            {"id": "cartao_sicoob", "nome": "Cartão Sicoob", "tipo": "cartao", "nCodCC": 11574015480},
            {"id": "cartao_itau", "nome": "Cartão Itaú", "tipo": "cartao", "nCodCC": 11693512362},
        ],
    })

# --- Prime Sol Lagos ---
_key, _secret = _credenciais("OMIE_APP_KEY_LAGOS", "OMIE_APP_SECRET_LAGOS")
if _key and _secret:
    EMPRESAS.append({
        "id": "lagos",
        "nome": "Prime Sol Lagos",
        "app_key": _key,
        "app_secret": _secret,
        "contas": [
            {"id": "sicoob_lagos", "nome": "Sicoob Lagos", "tipo": "banco", "nCodCC": 10113758384},
            {"id": "mastercard_lagos", "nome": "MasterCard", "tipo": "cartao", "nCodCC": 10453329672},
        ],
    })

# --- Prime Sol Cabo Frio ---
_key, _secret = _credenciais("OMIE_APP_KEY_CABO_FRIO", "OMIE_APP_SECRET_CABO_FRIO")
if _key and _secret:
    EMPRESAS.append({
        "id": "cabo_frio",
        "nome": "Prime Sol Cabo Frio",
        "app_key": _key,
        "app_secret": _secret,
        "contas": [
            {"id": "sicoob_cabo_frio", "nome": "Sicoob CB Frio", "tipo": "banco", "nCodCC": 11471508388},
        ],
    })

# --- PS Energia ---
_key, _secret = _credenciais("OMIE_APP_KEY_PS_ENERGIA", "OMIE_APP_SECRET_PS_ENERGIA")
if _key and _secret:
    EMPRESAS.append({
        "id": "ps_energia",
        "nome": "PS Energia",
        "app_key": _key,
        "app_secret": _secret,
        "contas": [
            {"id": "banco_inter", "nome": "Banco Inter", "tipo": "banco", "nCodCC": 11441838685},
        ],
    })


def chamar_omie(modulo: str, call: str, param: dict, app_key: str, app_secret: str, tentativas: int = 4) -> dict:
    """Faz uma chamada genérica à API da Omie, para a empresa (App Key/
    Secret) indicada.

    Inclui uma pequena pausa antes de cada chamada (para não estourar o
    limite de requisições por segundo da Omie) e tenta de novo, com pausas
    crescentes, se der erro temporário (500, 425, 429 ou timeout) — sem
    isso, uma sequência de erros rápidos vira um "efeito cascata" onde a
    Omie passa a bloquear todas as chamadas seguintes.
    """
    url = f"{BASE_URL}/{modulo}/"
    payload = {
        "call": call,
        "app_key": app_key,
        "app_secret": app_secret,
        "param": [param],
    }

    ultimo_erro = None
    for tentativa in range(1, tentativas + 1):
        time.sleep(0.4)  # pausa fixa entre chamadas, para não estourar o limite de requisições
        try:
            resp = requests.post(url, headers=HEADERS, json=payload, timeout=30)
            resp.raise_for_status()
            data = resp.json()
            if "faultstring" in data:
                raise RuntimeError(f"Erro Omie ({call}): {data['faultstring']}")
            return data
        except (requests.exceptions.HTTPError, requests.exceptions.Timeout) as erro:
            ultimo_erro = erro
            status = getattr(getattr(erro, "response", None), "status_code", None)
            if status in (429, 425, 500, 502, 503, 504) or isinstance(erro, requests.exceptions.Timeout):
                espera = 2 ** tentativa  # 2s, 4s, 8s, 16s
                print(f"AVISO: erro temporário ({status or 'timeout'}) em {call}, tentativa {tentativa}/{tentativas}. Aguardando {espera}s...")
                time.sleep(espera)
                continue
            raise  # erro que não é de rate-limit/temporário: propaga na hora

    raise ultimo_erro


def gerar_meses(data_inicial: str, data_final: str) -> list:
    """Gera uma lista de (inicio, fim) por mês, no formato dd/mm/aaaa,
    para evitar que uma única chamada ultrapasse o limite de registros
    da Omie (a API não expõe paginação para o extrato)."""
    d_ini = datetime.strptime(data_inicial, "%d/%m/%Y")
    d_fim = datetime.strptime(data_final, "%d/%m/%Y")

    intervalos = []
    atual = d_ini.replace(day=1)
    while atual <= d_fim:
        if atual.month == 12:
            proximo_mes = atual.replace(year=atual.year + 1, month=1, day=1)
        else:
            proximo_mes = atual.replace(month=atual.month + 1, day=1)
        fim_mes = min(proximo_mes - timedelta(days=1), d_fim)
        inicio_intervalo = max(atual, d_ini)
        intervalos.append((
            inicio_intervalo.strftime("%d/%m/%Y"),
            fim_mes.strftime("%d/%m/%Y"),
        ))
        atual = proximo_mes
    return intervalos


def buscar_extrato(nCodCC: int, app_key: str, app_secret: str) -> dict:
    """Busca o extrato completo de uma conta, mês a mês, para evitar
    truncamento pelo limite de 100 registros por chamada da Omie.

    Retorna também o saldo anterior ao período total (necessário para
    calcular o saldo em datas onde ainda não há lançamento no período).
    """
    meses = gerar_meses(PERIODO_INICIAL, PERIODO_FINAL)
    todos_movimentos = []
    saldo_anterior_total = None

    for i, (ini, fim) in enumerate(meses):
        data = chamar_omie(
            "financas/extrato",
            "ListarExtrato",
            {
                "nCodCC": nCodCC,
                "cCodIntCC": "",
                "dPeriodoInicial": ini,
                "dPeriodoFinal": fim,
            },
            app_key,
            app_secret,
        )
        if i == 0:
            saldo_anterior_total = data.get("nSaldoAnterior", 0)
        todos_movimentos.extend(data.get("listaMovimentos", []) or [])

    return {
        "saldoAnterior": saldo_anterior_total or 0,
        "movimentos": todos_movimentos,
    }


def buscar_departamentos_cadastro(app_key: str, app_secret: str) -> dict:
    """Busca a tabela de departamentos cadastrados (código -> nome), da
    empresa correspondente às credenciais informadas. É uma lista pequena
    e estável, buscada uma única vez por empresa. Se falhar, retorna
    vazio — nesse caso os códigos de departamento aparecem "crus" no
    dashboard em vez do nome, mas o script não trava."""
    todos = []
    pagina = 1
    while True:
        try:
            data = chamar_omie(
                "geral/departamentos",
                "ListarDepartamentos",
                {"pagina": pagina, "registros_por_pagina": 100},
                app_key,
                app_secret,
            )
        except Exception as erro:
            print(f"AVISO: falha ao buscar catálogo de departamentos (página {pagina}): {erro}")
            break
        lote = data.get("departamentos", []) or []
        todos.extend(lote)
        total_paginas = data.get("total_de_paginas", 1)
        if pagina >= total_paginas or not lote:
            break
        pagina += 1
    return {d["codigo"]: d["descricao"] for d in todos}


def buscar_movimentos_financeiros(nCodCC: int, nomes_departamento: dict, app_key: str, app_secret: str) -> dict:
    """Busca os Movimentos Financeiros de uma conta (mês a mês, para evitar
    o limite de registros por chamada), pedindo a distribuição por
    departamento. Monta {nCodMovCC: {"departamento": ..., "observacao": ...}}.

    nCodMovCC é o mesmo código que aparece no extrato bancário como
    nCodLancamento — essa é a ponte confirmada entre os dois endpoints.

    A "observacao" aqui é a observação real do TÍTULO (Contas a Pagar/
    Receber) — diferente da observação do extrato bancário, que às vezes
    só traz uma mensagem genérica de importação/integração do banco.

    Se alguma chamada falhar (a Omie retornou erro 500 em algumas
    combinações de conta/mês/página durante os testes), o erro é
    registrado e a busca segue para o próximo mês, em vez de travar o
    script inteiro — melhor ter dados incompletos do que o dashboard
    inteiro não ser publicado.
    """
    lookup = {}
    for ini, fim in gerar_meses(PERIODO_INICIAL, PERIODO_FINAL):
        pagina = 1
        while True:
            try:
                data = chamar_omie(
                    "financas/mf",
                    "ListarMovimentos",
                    {
                        "nPagina": pagina,
                        "nRegPorPagina": 100,
                        "nCodCC": nCodCC,
                        "dDtPrevDe": ini,
                        "dDtPrevAte": fim,
                        "cExibirDepartamentos": "S",
                    },
                    app_key,
                    app_secret,
                )
            except Exception as erro:
                print(
                    f"AVISO: falha ao buscar movimentos financeiros (conta {nCodCC}, "
                    f"período {ini}-{fim}, página {pagina}): {erro}"
                )
                break

            movimentos = data.get("movimentos", []) or []
            for mov in movimentos:
                detalhes = mov.get("detalhes", {}) or {}
                cod_mov = detalhes.get("nCodMovCC")
                if not cod_mov:
                    continue

                deptos = mov.get("departamentos") or []
                if not deptos:
                    desc_depto = "-"
                elif len(deptos) == 1:
                    cod_dep = deptos[0].get("cCodDepartamento")
                    desc_depto = nomes_departamento.get(cod_dep, cod_dep or "-")
                else:
                    partes = []
                    for d in deptos:
                        cod_dep = d.get("cCodDepartamento")
                        nome = nomes_departamento.get(cod_dep, cod_dep or "-")
                        pct = d.get("nDistrPercentual", 0)
                        partes.append(f"{nome} ({pct:.0f}%)")
                    desc_depto = "; ".join(partes)

                observacao_titulo = (detalhes.get("observacao") or "").strip()
                status_titulo = (detalhes.get("cStatus") or "").strip()

                lookup[cod_mov] = {
                    "departamento": desc_depto,
                    "observacao": observacao_titulo,
                    "status": status_titulo,
                }

            total_paginas = data.get("nTotPaginas", 1)
            if pagina >= total_paginas or not movimentos:
                break
            pagina += 1
    return lookup


def montar_lookup_titulos(contas: list, app_key: str, app_secret: str) -> dict:
    """Monta {nCodMovCC: {"departamento": ..., "observacao": ...}} cruzando
    o cadastro de departamentos com os Movimentos Financeiros de cada
    conta de UMA empresa (identificada pelas credenciais informadas)."""
    nomes_departamento = buscar_departamentos_cadastro(app_key, app_secret)
    lookup_geral = {}
    for conta in contas:
        lookup_conta = buscar_movimentos_financeiros(conta["nCodCC"], nomes_departamento, app_key, app_secret)
        lookup_geral.update(lookup_conta)
    return lookup_geral


def coletar_dados() -> list:
    """Coleta os dados brutos de todas as EMPRESAS e suas contas, sem
    aplicar nenhum filtro. Cada conta resultante carrega também o nome
    da empresa à qual pertence."""
    resultado = []

    for empresa in EMPRESAS:
        contas = empresa["contas"]
        if not contas:
            print(f"AVISO: {empresa['nome']} não tem contas configuradas ainda — pulando.")
            continue

        # O endpoint de Movimentos Financeiros (usado para departamento e
        # situação do título) só funciona para contas bancárias — em todos
        # os testes, contas do tipo cartão retornaram erro 500 nele. Por
        # isso, pulamos os cartões aqui (eles simplesmente ficam com "-"
        # nesses dois campos), economizando um tempo enorme de tentativas
        # que sempre falhariam mesmo.
        contas_bancarias = [c for c in contas if c["tipo"] == "banco"]
        lookup_titulos = montar_lookup_titulos(contas_bancarias, empresa["app_key"], empresa["app_secret"])

        for conta in contas:
            extrato = buscar_extrato(conta["nCodCC"], empresa["app_key"], empresa["app_secret"])
            lancamentos = []
            for m in extrato["movimentos"]:
                cod_mov = m.get("nCodLancamento") or m.get("nCodLancRelac")
                info_titulo = lookup_titulos.get(cod_mov, {})

                # Prioriza a observação real do título (Contas a Pagar/Receber);
                # se não tiver, cai para a observação do extrato bancário (que
                # às vezes só tem uma mensagem genérica de importação/conciliação).
                observacao_titulo = info_titulo.get("observacao", "")
                observacao_extrato = (m.get("cObservacoes") or "").strip()
                observacao_final = observacao_titulo or observacao_extrato or "-"

                lancamentos.append({
                    "data": m.get("dDataLancamento", ""),
                    "cliente": m.get("cDesCliente", "-") or "-",
                    "valor": m.get("nValorDocumento", 0),
                    "situacao": m.get("cSituacao", "-") or "-",
                    "situacaoTitulo": info_titulo.get("status") or "-",
                    "dataConciliacao": (m.get("dDataConciliacao") or "").strip(),
                    "saldo": m.get("nSaldo", 0),
                    "categoria": m.get("cDesCategoria", "-") or "-",
                    "observacao": observacao_final,
                    "departamento": info_titulo.get("departamento", "-"),
                })

            resultado.append({
                "id": f"{empresa['id']}_{conta['id']}",
                "nome": conta["nome"],
                "tipo": conta["tipo"],
                "empresa": empresa["nome"],
                "saldoAnterior": extrato["saldoAnterior"],
                "lancamentos": lancamentos,
            })

    return resultado


def gerar_html(contas: list) -> str:
    agora = datetime.now(timezone.utc).strftime("%d/%m/%Y %H:%M UTC")
    dados_json = jsonlib.dumps(contas, ensure_ascii=False)

    empresas_unicas = list(dict.fromkeys(c["empresa"] for c in contas))
    checkboxes_empresa_html = "".join(
        f'<label><input type="checkbox" class="chk-empresa" value="{nome}" checked> {nome}</label>'
        for nome in empresas_unicas
    )

    return f"""<!DOCTYPE html>
<html lang="pt-BR">
<head>
<meta charset="UTF-8">
<title>Dashboard Prime Sol — Financeiro</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  :root {{
    color-scheme: dark;
    --bg: #0b1220;
    --bg-panel: #131c2e;
    --bg-card: #17223a;
    --border: #263248;
    --text: #e7ecf5;
    --text-muted: #8b96ab;
    --text-faint: #5b6780;
    --accent: #4169e8;
    --accent-hover: #365bdd;
    --laranja: #faa821;
    --laranja-hover: #e8960f;
    --green: #4ade80;
    --red: #f87171;
    --cyan: #7dd3fc;
    --radius: 12px;
    --radius-sm: 8px;
    --space: 8px;
  }}

  * {{ box-sizing: border-box; }}

  body {{ font-family: -apple-system, "Segoe UI", Roboto, sans-serif; margin: 0; background: var(--bg); color: var(--text); line-height: 1.4; }}

  header {{ padding: 20px 32px; background: var(--bg-panel); border-bottom: 1px solid var(--border); display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 12px; }}
  .marca {{ display: flex; align-items: center; gap: 14px; }}
  .marca-logo {{ height: 42px; width: auto; }}
  .marca-texto {{ display: flex; flex-direction: column; line-height: 1.2; }}
  .marca-nome {{ font-size: 19px; font-weight: 800; letter-spacing: 0.02em; color: var(--text); }}
  .marca-destaque {{ color: var(--laranja); }}
  .marca-sub {{ font-size: 11.5px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.08em; color: var(--text-faint); margin-top: 2px; }}
  .atualizado {{ color: var(--text-muted); font-size: 12.5px; }}

  .filtros {{
    padding: 20px 32px;
    background: var(--bg-panel);
    border-bottom: 1px solid var(--border);
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(180px, auto));
    gap: 24px;
    align-items: start;
  }}
  .filtro-bloco {{ display: flex; flex-direction: column; gap: 10px; min-height: 62px; }}
  .filtro-bloco h3 {{
    font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: .06em;
    color: var(--text-faint); margin: 0;
  }}
  .grupo-check {{ display: flex; flex-direction: column; gap: 5px; margin-bottom: 8px; font-size: 13px; }}
  .grupo-check:last-child {{ margin-bottom: 0; }}
  .grupo-check strong {{ font-size: 10.5px; color: var(--text-faint); text-transform: uppercase; letter-spacing: .04em; margin-bottom: 2px; }}
  .grupo-check label {{ display: flex; align-items: center; gap: 8px; cursor: pointer; color: var(--text); }}
  .grupo-check input[type="checkbox"] {{ accent-color: var(--accent); width: 14px; height: 14px; }}

  .datas {{ display: flex; gap: 12px; align-items: center; font-size: 12.5px; flex-wrap: wrap; }}
  .datas label {{ display: flex; align-items: center; gap: 6px; color: var(--text-muted); }}
  .datas input, .input-texto, .input-valor {{
    background: var(--bg); border: 1px solid var(--border); color: var(--text);
    border-radius: var(--radius-sm); padding: 7px 9px; font-size: 12.5px;
  }}
  .datas input:focus, .input-texto:focus, .input-valor:focus {{ outline: none; border-color: var(--accent); }}
  .input-texto {{ width: 180px; }}
  .input-valor {{ width: 88px; }}

  .radios {{ display: flex; flex-direction: column; gap: 7px; font-size: 13px; }}
  .radios label {{ display: flex; align-items: center; gap: 8px; cursor: pointer; }}
  .radios input[type="radio"] {{ accent-color: var(--accent); width: 14px; height: 14px; }}

  .botoes-filtro {{ display: flex; gap: 8px; align-self: end; }}

  #btnAplicar {{
    background: var(--accent); color: white; border: none; border-radius: var(--radius-sm);
    padding: 0 22px; height: 40px; font-size: 13px; font-weight: 600; cursor: pointer;
    transition: background .15s ease;
  }}
  #btnAplicar:hover {{ background: var(--accent-hover); }}

  #btnRedefinir {{
    background: transparent; color: var(--text-muted); border: 1px solid var(--border); border-radius: var(--radius-sm);
    padding: 0 18px; height: 40px; font-size: 13px; font-weight: 600; cursor: pointer;
    transition: all .15s ease;
  }}
  #btnRedefinir:hover {{ background: var(--border); color: var(--text); }}

  .saldos, .cards {{
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
    gap: 10px;
    padding: 16px 32px 0;
  }}

  .box-saldo {{
    background: linear-gradient(180deg, #0f2942 0%, #0d2338 100%);
    border: 1px solid #1d4d7a;
    border-radius: var(--radius-sm);
    padding: 10px 12px;
  }}
  .box-saldo .label {{ font-size: 9.5px; font-weight: 700; color: var(--cyan); text-transform: uppercase; letter-spacing: .04em; }}
  .box-saldo .valor-saldo {{ font-size: 16px; font-weight: 800; margin-top: 4px; color: #f0f9ff; letter-spacing: -0.01em; }}
  .box-saldo .ref {{ font-size: 9.5px; color: var(--text-faint); margin-top: 4px; }}

  .saldo-total-wrap {{ padding: 16px 32px 0; }}
  .card-saldo-total {{
    background: linear-gradient(135deg, #1a2f14 0%, #16321f 60%, #0f2942 100%);
    border: 1px solid #2d6a3e;
    border-radius: var(--radius-sm);
    padding: 13px 18px;
    display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 10px;
  }}
  .card-saldo-total .label {{
    font-size: 11px; font-weight: 800; color: #6ee7a0; text-transform: uppercase; letter-spacing: .05em;
  }}
  .card-saldo-total .ref {{ font-size: 10px; color: var(--text-faint); margin-top: 3px; }}
  .card-saldo-total .valor-saldo-total {{ font-size: 23px; font-weight: 800; color: #eafff2; letter-spacing: -0.01em; }}

  .card {{
    background: var(--bg-card); border-radius: var(--radius-sm); padding: 10px 12px;
    border: 1px solid var(--border); display: flex; flex-direction: column;
  }}
  .card .label {{
    font-size: 9.5px; font-weight: 700; color: var(--text-muted); text-transform: uppercase;
    letter-spacing: .04em; margin-bottom: 6px; padding-bottom: 5px; border-bottom: 1px solid var(--border);
  }}
  .linha-valor {{ display: flex; justify-content: space-between; align-items: baseline; gap: 8px; padding: 1px 0; }}
  .mini-label {{ font-size: 10px; color: var(--text-faint); }}
  .valor {{ font-size: 12px; font-weight: 700; }}
  .valor.entrada {{ color: var(--green); }}
  .valor.saida {{ color: var(--red); }}
  .valor.saldo {{ color: var(--text); font-size: 13.5px; }}
  .card .qtd {{ font-size: 9.5px; color: var(--text-faint); margin-top: 6px; padding-top: 5px; border-top: 1px solid var(--border); }}

  .card-departamento-wrap {{ padding: 0 32px; margin-top: 4px; }}
  .card-departamento {{ max-width: none; }}
  .card-departamento .label {{ margin-bottom: 8px; }}
  .linha-depto {{ display: flex; align-items: center; gap: 12px; padding: 6px 0; font-size: 13px; }}
  .linha-depto .nome-depto {{ flex: 0 0 200px; color: var(--text); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
  .linha-depto .barra-wrap {{ flex: 1; background: var(--bg); border-radius: 4px; height: 8px; overflow: hidden; }}
  .linha-depto .barra {{ height: 100%; background: var(--accent); border-radius: 4px; }}
  .linha-depto .pct-depto {{ flex: 0 0 52px; text-align: right; font-weight: 700; color: var(--text); }}
  .linha-depto .valor-depto {{ flex: 0 0 110px; text-align: right; color: var(--text-faint); font-size: 12px; }}

  section {{ padding: 12px 32px 40px; }}
  h2 {{
    font-size: 14.5px; font-weight: 700; color: var(--text); border-bottom: 1px solid var(--border);
    padding-bottom: 10px; margin: 32px 0 14px;
  }}
  section > div:first-child h2 {{ margin-top: 8px; }}

  .tabela-wrap {{ overflow-x: auto; border-radius: var(--radius-sm); }}
  .scroll-topo-wrap {{ overflow-x: auto; overflow-y: hidden; height: 14px; margin-bottom: 2px; }}
  .scroll-topo-inner {{ height: 1px; }}
  table {{ table-layout: fixed; border-collapse: collapse; margin-bottom: 8px; font-size: 12.5px; background: var(--bg-panel); }}
  th, td {{ text-align: left; padding: 9px 12px; border-bottom: 1px solid var(--border); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }}
  th {{ position: relative; color: var(--text-muted); font-weight: 600; white-space: nowrap; font-size: 11.5px; text-transform: uppercase; letter-spacing: .03em; }}
  th .th-ordenavel {{ overflow: hidden; text-overflow: ellipsis; white-space: nowrap; cursor: pointer; padding: 2px 4px; border-radius: 4px; }}
  th .th-ordenavel:hover {{ background: var(--border); color: var(--text); }}
  th .th-ordenavel.ativo {{ color: var(--laranja); }}
  tr:last-child td {{ border-bottom: none; }}
  tr.linha-total td {{ font-weight: 700; color: var(--text); background: var(--bg-panel); border-top: 2px solid var(--border); border-bottom: none; }}
  tr.linha-total .valor-total {{ color: var(--cyan); }}
  .vazio {{ color: var(--text-faint); font-size: 13px; padding: 16px 0; }}

  .resize-handle {{ position: absolute; top: 0; right: -4px; width: 14px; height: 100%; cursor: col-resize; user-select: none; z-index: 5; }}
  .resize-handle:hover, .resize-handle.resizando {{ background: var(--accent); opacity: 0.5; }}

  .btn-filtro-col {{ background: none; border: none; color: var(--text-faint); cursor: pointer; font-size: 11px; padding: 2px 5px; border-radius: 4px; margin-left: 3px; vertical-align: middle; }}
  .btn-filtro-col:hover {{ background: var(--border); color: var(--text); }}
  .btn-filtro-col.ativo {{ color: var(--green); font-weight: 700; }}

  .btn-largura {{ background: var(--border); border: none; color: var(--text); cursor: pointer; font-size: 11px; width: 16px; height: 16px; line-height: 16px; border-radius: 3px; padding: 0; margin-left: 2px; vertical-align: middle; }}
  .btn-largura:hover {{ background: var(--accent); }}

  .dropdown-filtro {{ position: fixed; background: var(--bg-card); border: 1px solid var(--border); border-radius: var(--radius-sm); padding: 10px; z-index: 1000; width: 240px; box-shadow: 0 12px 32px rgba(0,0,0,0.5); }}
  .dropdown-busca {{ width: 100%; box-sizing: border-box; background: var(--bg); border: 1px solid var(--border); color: var(--text); border-radius: 6px; padding: 6px 8px; font-size: 12px; margin-bottom: 8px; }}
  .dropdown-busca:focus {{ outline: none; border-color: var(--accent); }}
  .dropdown-acoes {{ display: flex; justify-content: space-between; margin-bottom: 6px; }}
  .dropdown-acoes button {{ background: none; border: none; color: var(--cyan); font-size: 11px; cursor: pointer; padding: 2px 4px; }}
  .dropdown-acoes button:hover {{ text-decoration: underline; }}
  .dropdown-lista {{ max-height: 220px; overflow-y: auto; border-top: 1px solid var(--border); border-bottom: 1px solid var(--border); padding: 6px 0; margin-bottom: 8px; }}
  .dropdown-item {{ display: flex; align-items: center; gap: 6px; font-size: 12px; padding: 4px 3px; cursor: pointer; border-radius: 4px; }}
  .dropdown-item:hover {{ background: var(--bg); }}
  .dropdown-item input {{ accent-color: var(--accent); }}
  .dropdown-ok {{ width: 100%; background: var(--accent); color: white; border: none; border-radius: 6px; padding: 7px; font-size: 12px; font-weight: 600; cursor: pointer; }}
  .dropdown-ok:hover {{ background: var(--accent-hover); }}
</style>
</head>
<body>
<header>
  <div class="marca">
    <img src="data:image/png;base64,{LOGO_BASE64}" alt="Prime Sol" class="marca-logo">
    <div class="marca-texto">
      <div class="marca-nome">PRIME <span class="marca-destaque">SOL</span></div>
      <div class="marca-sub">Dashboard Financeiro</div>
    </div>
  </div>
  <div class="atualizado">Última atualização: {agora} · Dados brutos coletados de {PERIODO_INICIAL} até {PERIODO_FINAL}</div>
</header>

<div class="filtros">
  <div class="filtro-bloco">
    <h3>Empresas</h3>
    <div class="grupo-check">
      {checkboxes_empresa_html}
    </div>
  </div>

  <div class="filtro-bloco">
    <h3>Período (data de previsão/pagamento)</h3>
    <div class="datas">
      <label>De: <input type="date" id="dataDe" value="2026-01-01"></label>
      <label>Até: <input type="date" id="dataAte"></label>
    </div>
  </div>

  <div class="filtro-bloco">
    <h3>Data de Conciliação</h3>
    <div class="datas">
      <label>De: <input type="date" id="conciliDe"></label>
      <label>Até: <input type="date" id="conciliAte"></label>
    </div>
  </div>

  <div class="filtro-bloco">
    <h3>Cliente / Fornecedor</h3>
    <input type="text" id="filtroCliente" placeholder="Buscar por nome..." class="input-texto">
  </div>

  <div class="filtro-bloco">
    <h3>Valor</h3>
    <div class="datas">
      <label>Mín: <input type="number" id="valorMin" step="0.01" placeholder="-9999" class="input-valor"></label>
      <label>Máx: <input type="number" id="valorMax" step="0.01" placeholder="9999" class="input-valor"></label>
    </div>
  </div>

  <div class="filtro-bloco">
    <h3>Situação</h3>
    <input type="text" id="filtroSituacao" placeholder="Ex: Pago, Agendado, A Vencer..." class="input-texto">
  </div>

  <div class="botoes-filtro">
    <button id="btnAplicar">Aplicar filtros</button>
    <button id="btnRedefinir" type="button">Redefinir filtros</button>
  </div>
</div>

<div class="saldo-total-wrap" id="saldoTotalContainer"></div>

<div class="saldos" id="saldosContainer"></div>

<div class="cards" id="cardsContainer"></div>

<div class="card-departamento-wrap">
  <div class="card card-departamento" id="cardDepartamentoContainer"></div>
</div>

<section id="secoesContainer"></section>

<script>
const DADOS = {dados_json};

// Definição das colunas da tabela, usadas tanto para montar o cabeçalho
// quanto para o filtro estilo Excel de cada coluna.
const COLUNAS = [
  {{ key: 'situacaoTitulo', label: 'Situação', get: l => l.situacaoTitulo }},
  {{ key: 'data', label: 'Data Previsão/Pagamento', get: l => l.data }},
  {{ key: 'empresa', label: 'Empresa', get: l => l.empresaNome }},
  {{ key: 'cliente', label: 'Cliente/Fornecedor', get: l => l.cliente }},
  {{ key: 'valor', label: 'Valor', get: l => fmtMoeda(l.valor) }},
  {{ key: 'categoria', label: 'Categoria', get: l => l.categoria }},
  {{ key: 'departamento', label: 'Departamento', get: l => l.departamento }},
  {{ key: 'conta', label: 'Banco/Cartão', get: l => l.contaNome }},
  {{ key: 'observacao', label: 'Observação', get: l => l.observacao }},
  {{ key: 'dataConciliacao', label: 'Data Conciliação', get: l => l.dataConciliacao || '-' }},
];

// Estado dos filtros de coluna (estilo Excel): chave "coluna" -> Set de valores permitidos.
// Ausência da chave = nenhum filtro ativo nessa coluna (mostra tudo).
let colFiltros = {{}};
// Guarda, a cada renderização, a lista combinada (todas as contas selecionadas)
// já filtrada pelo painel superior, usada para montar as opções de cada dropdown.
let baseFiltradosGlobal = [];

// Larguras de coluna (redimensionáveis pelo usuário, arrastando a borda do cabeçalho).
// Chave "coluna" -> largura em px. Sem entrada = usa o padrão abaixo.
let colWidths = {{}};
const LARGURA_PADRAO = {{
  situacaoTitulo: 130, conta: 150, empresa: 160, data: 150, cliente: 200, valor: 110, categoria: 160,
  observacao: 240, dataConciliacao: 150,
}};
let resizando = null;

// Estado de ordenação da tabela: null = ordem natural (como veio da Omie).
let ordenacao = {{ coluna: null, direcao: null }};

/** Extrai o valor "comparável" de um lançamento para uma coluna, usado na
 * ordenação — números continuam números, datas viram AAAA-MM-DD (ordena
 * cronologicamente certo), e texto vira minúsculo (ordena A-Z ignorando
 * maiúscula/minúscula). */
function valorOrdenacao(l, colKey) {{
  switch (colKey) {{
    case 'valor': return l.valor;
    case 'data': return paraDataISO(l.data) || '';
    case 'dataConciliacao': return paraDataISO(l.dataConciliacao) || '';
    case 'cliente': return (l.cliente || '').toLowerCase();
    case 'categoria': return (l.categoria || '').toLowerCase();
    case 'departamento': return (l.departamento || '').toLowerCase();
    case 'conta': return (l.contaNome || '').toLowerCase();
    case 'empresa': return (l.empresaNome || '').toLowerCase();
    case 'observacao': return (l.observacao || '').toLowerCase();
    case 'situacaoTitulo': return (l.situacaoTitulo || '').toLowerCase();
    default: return '';
  }}
}}

function paraDataISO(brDate) {{
  if (!brDate) return null;
  const partes = brDate.split('/');
  if (partes.length !== 3) return null;
  return `${{partes[2]}}-${{partes[1]}}-${{partes[0]}}`;
}}

function fmtMoeda(v) {{
  return 'R$ ' + v.toLocaleString('pt-BR', {{minimumFractionDigits: 2, maximumFractionDigits: 2}});
}}

function fmtDataBR(iso) {{
  if (!iso) return '';
  const [ano, mes, dia] = iso.split('-');
  return `${{dia}}/${{mes}}/${{ano}}`;
}}

/**
 * Calcula o saldo real da conta na data informada (dataAteISO), usando
 * TODOS os lançamentos da conta (não filtrados por conciliação), já que
 * o saldo bancário existe independente de já ter sido conciliado ou não.
 */
function calcularSaldoNaData(conta, dataAteISO) {{
  const ordenados = [...conta.lancamentos]
    .map(l => ({{...l, _iso: paraDataISO(l.data)}}))
    .filter(l => l._iso)
    .sort((a, b) => a._iso.localeCompare(b._iso));

  let saldo = conta.saldoAnterior;
  for (const l of ordenados) {{
    if (dataAteISO && l._iso > dataAteISO) break;
    saldo = l.saldo;
  }}
  return saldo;
}}

function empresasSelecionadas() {{
  return Array.from(document.querySelectorAll('.chk-empresa:checked')).map(el => el.value);
}}

function aplicarFiltrosColuna(lista) {{
  return lista.filter(l => {{
    return COLUNAS.every(col => {{
      const permitidos = colFiltros[col.key];
      if (!permitidos) return true;
      return permitidos.has(col.get(l));
    }});
  }});
}}

function fecharDropdowns() {{
  document.querySelectorAll('.dropdown-filtro').forEach(d => d.remove());
}}

document.addEventListener('click', (e) => {{
  if (!e.target.closest('.dropdown-filtro') && !e.target.closest('.btn-filtro-col')) {{
    fecharDropdowns();
  }}
}});

function abrirDropdownColuna(col, btnEl) {{
  fecharDropdowns();
  const selecionadosAtuais = colFiltros[col.key];
  const valoresUnicos = [...new Set(baseFiltradosGlobal.map(col.get))].sort();

  const dropdown = document.createElement('div');
  dropdown.className = 'dropdown-filtro';
  const rect = btnEl.getBoundingClientRect();
  dropdown.style.top = (rect.bottom + 4) + 'px';
  dropdown.style.left = Math.min(rect.left, window.innerWidth - 260) + 'px';

  dropdown.innerHTML = `
    <input type="text" class="dropdown-busca" placeholder="Buscar...">
    <div class="dropdown-acoes">
      <button type="button" class="dropdown-todos">Selecionar tudo</button>
      <button type="button" class="dropdown-nenhum">Limpar</button>
    </div>
    <div class="dropdown-lista"></div>
    <button type="button" class="dropdown-ok">Aplicar</button>
  `;

  const lista = dropdown.querySelector('.dropdown-lista');

  function renderLista(filtroTexto) {{
    lista.innerHTML = '';
    valoresUnicos
      .filter(v => !filtroTexto || (v || '').toLowerCase().includes(filtroTexto.toLowerCase()))
      .forEach(v => {{
        const marcado = !selecionadosAtuais || selecionadosAtuais.has(v);
        const item = document.createElement('label');
        item.className = 'dropdown-item';
        const valorEscapado = (v || '').replace(/"/g, '&quot;');
        item.innerHTML = `<input type="checkbox" value="${{valorEscapado}}" ${{marcado ? 'checked' : ''}}> <span>${{v || '(vazio)'}}</span>`;
        lista.appendChild(item);
      }});
  }}
  renderLista('');

  dropdown.querySelector('.dropdown-busca').addEventListener('input', (ev) => renderLista(ev.target.value));
  dropdown.querySelector('.dropdown-todos').addEventListener('click', () => {{
    dropdown.querySelectorAll('.dropdown-item input').forEach(chk => chk.checked = true);
  }});
  dropdown.querySelector('.dropdown-nenhum').addEventListener('click', () => {{
    dropdown.querySelectorAll('.dropdown-item input').forEach(chk => chk.checked = false);
  }});
  dropdown.querySelector('.dropdown-ok').addEventListener('click', () => {{
    const marcados = Array.from(dropdown.querySelectorAll('.dropdown-item input:checked')).map(c => c.value);
    if (marcados.length === valoresUnicos.length) {{
      delete colFiltros[col.key];
    }} else {{
      colFiltros[col.key] = new Set(marcados);
    }}
    fecharDropdowns();
    renderizar();
  }});

  document.body.appendChild(dropdown);
}}

function renderizar() {{
  const dataDe = document.getElementById('dataDe').value;
  const dataAte = document.getElementById('dataAte').value;
  const conciliDe = document.getElementById('conciliDe').value;
  const conciliAte = document.getElementById('conciliAte').value;
  const textoCliente = document.getElementById('filtroCliente').value.trim().toLowerCase();
  const textoSituacao = document.getElementById('filtroSituacao').value.trim().toLowerCase();
  const valorMinStr = document.getElementById('valorMin').value;
  const valorMaxStr = document.getElementById('valorMax').value;
  const valorMin = valorMinStr === '' ? null : parseFloat(valorMinStr);
  const valorMax = valorMaxStr === '' ? null : parseFloat(valorMaxStr);

  const cardsContainer = document.getElementById('cardsContainer');
  const saldosContainer = document.getElementById('saldosContainer');
  const secoesContainer = document.getElementById('secoesContainer');
  cardsContainer.innerHTML = '';
  saldosContainer.innerHTML = '';
  secoesContainer.innerHTML = '';

  const rotuloSaldo = (dataDe === dataAte)
    ? `Saldo em ${{fmtDataBR(dataAte)}}`
    : `Saldo ao final do período (${{fmtDataBR(dataAte)}})`;

  // Combina os lançamentos de TODAS as contas (não há mais checkbox de seleção
  // de conta — quem decide quais bancos/cartões aparecem é o filtro estilo
  // Excel na própria coluna "Banco/Cartão" da tabela).
  let todosLancamentos = [];
  const empresasChecadas = empresasSelecionadas();
  DADOS.forEach(conta => {{
    if (!empresasChecadas.includes(conta.empresa)) return;

    const baseFiltrados = conta.lancamentos.filter(l => {{
      const dataISO = paraDataISO(l.data);
      if (dataDe && dataISO && dataISO < dataDe) return false;
      if (dataAte && dataISO && dataISO > dataAte) return false;

      if (conciliDe || conciliAte) {{
        const conciliISO = paraDataISO(l.dataConciliacao);
        if (!conciliISO) return false;
        if (conciliDe && conciliISO < conciliDe) return false;
        if (conciliAte && conciliISO > conciliAte) return false;
      }}

      if (textoCliente && !(l.cliente || '').toLowerCase().includes(textoCliente)) return false;
      if (textoSituacao && !(l.situacaoTitulo || '').toLowerCase().includes(textoSituacao)) return false;

      if (valorMin !== null && l.valor < valorMin) return false;
      if (valorMax !== null && l.valor > valorMax) return false;

      return true;
    }});

    baseFiltrados.forEach(l => todosLancamentos.push({{
      ...l,
      contaNome: conta.nome,
      contaTipo: conta.tipo,
      empresaNome: conta.empresa,
    }}));
  }});

  // baseFiltradosGlobal (antes do filtro de coluna) alimenta as opções dos
  // dropdowns estilo Excel — assim a lista de bancos no dropdown da coluna
  // "Banco/Cartão" sempre mostra todos os disponíveis, mesmo os que estão
  // desmarcados no momento (comportamento padrão do Excel).
  baseFiltradosGlobal = todosLancamentos;
  const filtrados = aplicarFiltrosColuna(todosLancamentos);

  // --- Card único de distribuição por Departamento (% sobre o valor absoluto total filtrado) ---
  const cardDepto = document.getElementById('cardDepartamentoContainer');
  const totalAbsDepto = filtrados.reduce((s, l) => s + Math.abs(l.valor), 0);
  const somaPorDepto = {{}};
  filtrados.forEach(l => {{
    const chave = l.departamento || '-';
    somaPorDepto[chave] = (somaPorDepto[chave] || 0) + Math.abs(l.valor);
  }});
  const linhasDepto = Object.entries(somaPorDepto)
    .sort((a, b) => b[1] - a[1])
    .map(([nome, valor]) => {{
      const pct = totalAbsDepto > 0 ? (valor / totalAbsDepto * 100) : 0;
      return `
        <div class="linha-depto">
          <span class="nome-depto">${{nome}}</span>
          <div class="barra-wrap"><div class="barra" style="width:${{pct.toFixed(1)}}%"></div></div>
          <span class="pct-depto">${{pct.toFixed(1)}}%</span>
          <span class="valor-depto">${{fmtMoeda(valor)}}</span>
        </div>
      `;
    }}).join('');
  cardDepto.innerHTML = `
    <div class="label">Distribuição por Departamento (sobre o total filtrado)</div>
    ${{linhasDepto || '<div class="vazio">Nenhum lançamento encontrado com os filtros atuais.</div>'}}
  `;

  // Cards e caixas de saldo agora seguem o resultado FINAL da tabela
  // (incluindo o filtro de coluna "Banco/Cartão"), agrupando por conta.
  const contasPresentes = [...new Set(filtrados.map(l => l.contaNome))];

  // Soma do saldo real (não é a soma de entradas/saídas do período — é o
  // saldo bancário de fato) de todas as contas BANCÁRIAS visíveis no
  // momento. Cartão de crédito fica de fora, porque saldo de cartão não é
  // "dinheiro em caixa" de verdade.
  let saldoTotalBancos = 0;

  contasPresentes.forEach(nomeConta => {{
    const dadosConta = DADOS.find(c => c.nome === nomeConta);
    const doConta = filtrados.filter(l => l.contaNome === nomeConta);

    if (dadosConta) {{
      const saldoConta = calcularSaldoNaData(dadosConta, dataAte);
      if (dadosConta.tipo === 'banco') {{
        saldoTotalBancos += saldoConta;
      }}
      const boxSaldo = document.createElement('div');
      boxSaldo.className = 'box-saldo';
      boxSaldo.innerHTML = `
        <div class="label">${{nomeConta}}</div>
        <div class="valor-saldo">${{fmtMoeda(saldoConta)}}</div>
        <div class="ref">${{rotuloSaldo}}</div>
      `;
      saldosContainer.appendChild(boxSaldo);
    }}

    const entradas = doConta.filter(l => l.valor > 0).reduce((s, l) => s + l.valor, 0);
    const saidas = doConta.filter(l => l.valor < 0).reduce((s, l) => s + l.valor, 0);
    const saldo = entradas + saidas;
    const tipoLabel = (dadosConta && dadosConta.tipo === 'banco') ? 'Conta Bancária' : 'Cartão de Crédito';

    const card = document.createElement('div');
    card.className = 'card';
    card.innerHTML = `
      <div class="label">${{nomeConta}} — ${{tipoLabel}}</div>
      <div class="linha-valor"><span class="mini-label">Entradas</span><span class="valor entrada">${{fmtMoeda(entradas)}}</span></div>
      <div class="linha-valor"><span class="mini-label">Saídas</span><span class="valor saida">${{fmtMoeda(saidas)}}</span></div>
      <div class="linha-valor"><span class="mini-label">Saldo</span><span class="valor saldo">${{fmtMoeda(saldo)}}</span></div>
      <div class="qtd">${{doConta.length}} lançamento(s)</div>
    `;
    cardsContainer.appendChild(card);
  }});

  const saldoTotalContainer = document.getElementById('saldoTotalContainer');
  const rotuloSaldoTotal = (dataDe === dataAte)
    ? `Saldo em caixa em ${{fmtDataBR(dataAte)}} — soma de todas as contas bancárias visíveis`
    : `Saldo em caixa ao final do período (${{fmtDataBR(dataAte)}}) — soma de todas as contas bancárias visíveis`;
  saldoTotalContainer.innerHTML = `
    <div class="card-saldo-total">
      <div>
        <div class="label">Saldo Total</div>
        <div class="ref">${{rotuloSaldoTotal}}</div>
      </div>
      <div class="valor-saldo-total">${{fmtMoeda(saldoTotalBancos)}}</div>
    </div>
  `;

  // Ordenação (se o usuário clicou em algum cabeçalho de coluna) — feita
  // sobre TODOS os filtrados, antes de cortar para a amostra de 100, para
  // que o corte reflita de verdade os maiores/menores ou A-Z/Z-A.
  if (ordenacao.coluna) {{
    filtrados.sort((a, b) => {{
      const va = valorOrdenacao(a, ordenacao.coluna);
      const vb = valorOrdenacao(b, ordenacao.coluna);
      const cmp = (typeof va === 'number' && typeof vb === 'number')
        ? va - vb
        : String(va).localeCompare(String(vb), 'pt-BR');
      return ordenacao.direcao === 'desc' ? -cmp : cmp;
    }});
  }}

  const amostra = filtrados.slice(0, 100);

  const totalFiltrado = filtrados.reduce((s, l) => s + l.valor, 0);
  const indiceColunaValor = COLUNAS.findIndex(c => c.key === 'valor');
  const celulasTotal = COLUNAS.map((col, i) => {{
    if (i === indiceColunaValor) return `<td class="valor-total">${{fmtMoeda(totalFiltrado)}}</td>`;
    if (i === 0) return `<td>Total filtrado (${{filtrados.length}} lançamento(s))</td>`;
    return '<td></td>';
  }}).join('');
  const linhaTotalHtml = `<tr class="linha-total">${{celulasTotal}}</tr>`;

  const linhasHtml = amostra.map(l => `
    <tr>
      <td>${{l.situacaoTitulo}}</td>
      <td>${{l.data}}</td>
      <td>${{l.empresaNome}}</td>
      <td>${{l.cliente}}</td>
      <td>${{fmtMoeda(l.valor)}}</td>
      <td>${{l.categoria}}</td>
      <td>${{l.departamento}}</td>
      <td>${{l.contaNome}}</td>
      <td class="celula-obs" title="${{(l.observacao || '').replace(/"/g, '&quot;')}}">${{l.observacao}}</td>
      <td>${{l.dataConciliacao || '-'}}</td>
    </tr>
  `).join('');

  const headerHtml = COLUNAS.map(col => {{
    const ativo = colFiltros[col.key] ? 'ativo' : '';
    const largura = colWidths[col.key] || LARGURA_PADRAO[col.key] || 150;
    const ordenandoEsta = ordenacao.coluna === col.key;
    const seta = ordenandoEsta ? (ordenacao.direcao === 'asc' ? ' ▲' : ' ▼') : '';
    const classeOrdenacao = ordenandoEsta ? 'th-ordenavel ativo' : 'th-ordenavel';
    return `<th style="width:${{largura}}px">
      <span class="${{classeOrdenacao}}" data-col="${{col.key}}" title="Clique para ordenar">${{col.label}}${{seta}}</span>
      <button type="button" class="btn-filtro-col ${{ativo}}" data-col="${{col.key}}">▾</button>
      <button type="button" class="btn-largura" data-col="${{col.key}}" data-delta="-20" title="Diminuir largura">−</button>
      <button type="button" class="btn-largura" data-col="${{col.key}}" data-delta="20" title="Aumentar largura">+</button>
      <div class="resize-handle" data-col="${{col.key}}"></div>
    </th>`;
  }}).join('');

  // table-layout:fixed só respeita as larguras das colunas se a própria <table>
  // tiver uma largura explícita — sem isso, o navegador ignora nossos valores
  // e recalcula pelo conteúdo. Por isso somamos e aplicamos aqui.
  const larguraTotalTabela = COLUNAS.reduce(
    (soma, col) => soma + (colWidths[col.key] || LARGURA_PADRAO[col.key] || 150),
    0
  );

  const secao = document.createElement('div');
  secao.innerHTML = `
    <h2>Lançamentos (amostra de até 100, de ${{filtrados.length}} filtrados)</h2>
    ${{amostra.length ? `
      <div class="scroll-topo-wrap" id="scrollTopoWrap">
        <div class="scroll-topo-inner" id="scrollTopoInner"></div>
      </div>
      <div class="tabela-wrap" id="tabelaWrap">
        <table style="width:${{larguraTotalTabela}}px">
          <tr>${{headerHtml}}</tr>
          ${{linhasHtml}}
          ${{linhaTotalHtml}}
        </table>
      </div>
    ` : '<div class="vazio">Nenhum lançamento encontrado com os filtros atuais.</div>'}}
  `;
  secoesContainer.appendChild(secao);

  // Sincroniza a barra de rolagem de cima com a de baixo, para não precisar
  // descer até o fim da tabela toda vez que quiser arrastar para o lado.
  if (amostra.length) {{
    const scrollTopoWrap = document.getElementById('scrollTopoWrap');
    const scrollTopoInner = document.getElementById('scrollTopoInner');
    const tabelaWrapEl = document.getElementById('tabelaWrap');
    scrollTopoInner.style.width = larguraTotalTabela + 'px';

    let sincronizando = false;
    scrollTopoWrap.addEventListener('scroll', () => {{
      if (sincronizando) return;
      sincronizando = true;
      tabelaWrapEl.scrollLeft = scrollTopoWrap.scrollLeft;
      sincronizando = false;
    }});
    tabelaWrapEl.addEventListener('scroll', () => {{
      if (sincronizando) return;
      sincronizando = true;
      scrollTopoWrap.scrollLeft = tabelaWrapEl.scrollLeft;
      sincronizando = false;
    }});
  }}
}}

// Delegação de clique para os botões de filtro de coluna (eles são recriados a cada renderização).
document.getElementById('secoesContainer').addEventListener('click', (e) => {{
  const thOrdenavel = e.target.closest('.th-ordenavel');
  if (thOrdenavel) {{
    const colKey = thOrdenavel.dataset.col;
    if (ordenacao.coluna !== colKey) {{
      ordenacao = {{ coluna: colKey, direcao: 'asc' }};
    }} else if (ordenacao.direcao === 'asc') {{
      ordenacao = {{ coluna: colKey, direcao: 'desc' }};
    }} else {{
      ordenacao = {{ coluna: null, direcao: null }};
    }}
    renderizar();
    return;
  }}

  const btnLargura = e.target.closest('.btn-largura');
  if (btnLargura) {{
    const colKey = btnLargura.dataset.col;
    const delta = parseInt(btnLargura.dataset.delta, 10);
    const larguraAtual = colWidths[colKey] || LARGURA_PADRAO[colKey] || 150;
    colWidths[colKey] = Math.max(60, larguraAtual + delta);
    renderizar();
    return;
  }}

  const btn = e.target.closest('.btn-filtro-col');
  if (!btn) return;
  const colKey = btn.dataset.col;
  const col = COLUNAS.find(c => c.key === colKey);
  if (col) abrirDropdownColuna(col, btn);
}});

// Redimensionamento de colunas (arrastar a borda direita do cabeçalho).
document.getElementById('secoesContainer').addEventListener('mousedown', (e) => {{
  const handle = e.target.closest('.resize-handle');
  if (!handle) return;
  e.preventDefault();
  const th = handle.closest('th');
  resizando = {{
    colKey: handle.dataset.col,
    startX: e.clientX,
    startWidth: th.offsetWidth,
    th,
    handle,
  }};
  handle.classList.add('resizando');
  document.body.style.cursor = 'col-resize';
}});

document.addEventListener('mousemove', (e) => {{
  if (!resizando) return;
  const delta = e.clientX - resizando.startX;
  const novaLargura = Math.max(60, resizando.startWidth + delta);
  resizando.th.style.width = novaLargura + 'px';
}});

document.addEventListener('mouseup', () => {{
  if (!resizando) return;
  colWidths[resizando.colKey] = resizando.th.offsetWidth;
  resizando.handle.classList.remove('resizando');
  resizando = null;
  document.body.style.cursor = '';
  renderizar();
}});

window.addEventListener('blur', () => {{
  if (!resizando) return;
  resizando.handle.classList.remove('resizando');
  resizando = null;
  document.body.style.cursor = '';
}});

// Data "até" default = hoje
document.getElementById('dataAte').value = new Date().toISOString().split('T')[0];

function redefinirFiltros() {{
  // Painel superior: volta cada campo ao estado inicial.
  document.getElementById('dataDe').value = '2026-01-01';
  document.getElementById('dataAte').value = new Date().toISOString().split('T')[0];
  document.getElementById('conciliDe').value = '';
  document.getElementById('conciliAte').value = '';
  document.getElementById('filtroCliente').value = '';
  document.getElementById('valorMin').value = '';
  document.getElementById('valorMax').value = '';
  document.getElementById('filtroSituacao').value = '';
  document.querySelectorAll('.chk-empresa').forEach(chk => chk.checked = true);

  // Estado interno: filtro estilo Excel por coluna, larguras e ordenação.
  colFiltros = {{}};
  colWidths = {{}};
  ordenacao = {{ coluna: null, direcao: null }};

  fecharDropdowns();
  renderizar();
}}

document.getElementById('btnAplicar').addEventListener('click', renderizar);
document.getElementById('btnRedefinir').addEventListener('click', redefinirFiltros);
renderizar();
</script>

</body>
</html>
"""


def main():
    contas = coletar_dados()
    html = gerar_html(contas)

    os.makedirs("public", exist_ok=True)
    with open("public/index.html", "w", encoding="utf-8") as f:
        f.write(html)

    print("Dashboard gerado em public/index.html")


if __name__ == "__main__":
    main()
